### ISSUE TITLE
Smaller APBS data output files

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#101]
There is some need for smaller APBS output files; particularly for applications which need to transfer these data files (currently in OpenDX format) back and forth across a network.

However, OpenDX is fairly widely accepted/supported, so this might be a low-impact modification to the code and should probably be attempted in the context of a specific application: e.g., PDB2PQR/APBS web services.

I think @lizutah has some ideas on other scalar data formats we should consider.

**Comment by lizutah** [comment]
easist solution is in #216.  closing.
