### ISSUE TITLE
Rebuild programmer.pdf

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#108]
Currently located here:
http://www.poissonboltzmann.org/apbs/programmer-s-guide

(soon to be located on the new web page)

**Comment by keith923** [comment]
The programmer html and pdf are in the binary distribution packages under: share/apbs/doc/programmer.

I can point Minju at it if she needs help.

**Comment by lizutah** [comment]
@mchun0630 - this is updated in the distribution.  Download the tar and upload the new version, please.

**Comment by mchun0630** [comment]
Uploaded!
