### ISSUE TITLE
Migrate task lists

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#112]
Figure out if which of these are still relevant:
http://www.poissonboltzmann.org/develop/task-lists

**Comment by lizutah** [comment]
@kmonson - do you know what this is about?
https://sites.google.com/a/poissonboltzmann.org/software/develop/task-lists/new-pdb2pqr-documentation
"examples section for documentation"

**Comment by lizutah** [comment]
Old issues with resolutions below: 

*Add "APBS References and Further Reading" section to documentation 	 	 
Exists here: http://www.poissonboltzmann.org/docs/reading-list/

*Create templates for APBS and PDB2PQR documentation lists for the main page 	 	 
not applicable

*Documentation of the TINKER interface 	 	 
https://github.com/Electrostatics/apbs-pdb2pqr/issues/356

*APBS MM/PBSA tutorial
https://github.com/Electrostatics/apbs-pdb2pqr/issues/357

*Provide a FAQ on electrostatic energies and better definitions 	 	 
This exits here: http://www.poissonboltzmann.org/docs/apbs-faq/

*Update or remove PMV tutorial
PMV is documented here: http://www.poissonboltzmann.org/docs/apbs-others/

*Improved programmer documentation
Resolved here: https://github.com/Electrostatics/apbs-pdb2pqr/issues/108

* Clean up wanted Wiki pages 	 	 
Not applicable

* Add documentation on the ways in which APBS interacts with other software packages, particularly ADT 	 	 
https://github.com/Electrostatics/apbs-pdb2pqr/issues/360

* Find a better pKa system than lysozyme 	 	 
https://github.com/Electrostatics/apbs-pdb2pqr/issues/361

*Migrate from MediaWiki
not applicable

*Finish Harwell-Boeing format documentation 	 	 
https://github.com/Electrostatics/apbs-pdb2pqr/issues/358

*Add SVN information 	 
No longer relevant

*Poisson-Boltzmann overview 	 	 
https://github.com/Electrostatics/apbs-pdb2pqr/issues/359

*Add mergedx documentation 	 	 
Appears here:  http://www.poissonboltzmann.org/docs/apbs-utilities/

Tutorials:

*APBS ligand relative binding example
I think this exists here: http://www.poissonboltzmann.org/examples/binding_energies/

*Nonpolar solvation energy tutorial and better definitions 	 	 
https://github.com/Electrostatics/apbs-pdb2pqr/issues/362

*Update or remove molecular simulation tutorial
https://github.com/Electrostatics/apbs-pdb2pqr/issues/363

*Update or remove solvation force tutorial
Updated with migration: http://www.poissonboltzmann.org/examples/potentials_of_mean_force/

**Comment by sobolevnrm** [comment]
https://sites.google.com/a/poissonboltzmann.org/software/develop/task-lists/new-pdb2pqr-documentation
is very old and can be deleted.

**Comment by lizutah** [comment]
With that...  I think all the old issues have either expired (no longer relevant), been migrated to GitHub, or already resolved.

**Comment by keith923** [comment]
Yay!!!!!
