### ISSUE TITLE
migrate "related software"

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#116]
Not going to include the "related software" category in the new site, so make sure the content on this page is still available.

**Comment by lizutah** [comment]
It looks like all the related software for APBS is updated.  @mchun0630, please check the pdb2pqr related software (https://sites.google.com/a/poissonboltzmann.org/software/pdb2pqr/related-software)

**Comment by mchun0630** [comment]
Links are already in place!
