### ISSUE TITLE
grid spacing documentation

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#148]
Need to add to the web site (maybe a FAQ?) and user documentation:

You should use the same grid for all three calculations:  ligand, protein, and ligand-protein complex.  I would recommend using the grid settings for the complex for all of them.

The energies are often very sensitive to grid parameters.  I recommend using the largest possible grid lengths with the smalls possible grid spacings for your calculations.

**Comment by lizutah** [comment]
@mchun0630 - please add to FAQ for apbs:  "What values should I use for my grid spacing?"

**Comment by sobolevnrm** [comment]
We usually recommend grid spacings of 0.5 Angstroms or smaller.

**Comment by mchun0630** [comment]
Finished and uploaded
