### ISSUE TITLE
update pymol documentation

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#182]
From Peter:
Hi Mr. Baker, I have finished following the APBS PyMol tutorial, I am attaching my notes. I mostly just followed the instructions (had to look up a few things), and I wrote down where I got stuck. I attached pictures of either making progress, or problems I encountered. Were there other things I was supposed to include in this write-up?

see email from 7/23, "PyMOL Access Link" from Nathan 
(Can't figure out how to attach a word document)

**Comment by lizutah** [comment]
@mchun0630 status on this?

**Comment by mchun0630** [comment]
@lizutah  I think peter said he made the updates, but I'm not sure, you can ask him later when he comes to work

**Comment by lizutah** [comment]
@pzli3
