### ISSUE TITLE
Broken links on server web page

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#198]
Most of the links on the pdb2pqr webserver http://nbcr-222.ucsd.edu/pdb2pqr_1.9.0/ are broken (with the exception of "PDB", "PROPKA", "Robert Hansen", and "pdb2pqr-users mailing list" (although it still links to the old sourceforge page as opposed to the google doc).

**Comment by lizutah** [comment]
@kmonson - these are still broken but this page shouldn't be used unless people have a link to this page.  Should we still fix these?

**Comment by lizutah** [comment]
@kmonson - can we remove the old page with the broken links, and redirect to the new one?

**Comment by kmonson** [comment]
We've officially removed 1.9 from NBCR.
