### ISSUE TITLE
Input files not listed in pdb2pqr query status page.

### ISSUE THREAD

**Issue by kmonson** [Electrostatics/apbs-pdb2pqr#206]
The list of input files on the query status page for a completed pdb2pqr job is incomplete and buggy. 

It does not include any file other then a user uploaded pdb file and only then if the file extension is correct.

User ligand, FF, and NAMES files are not included in the query status page.

**Comment by lizutah** [comment]
@kmonson did this get improved with the update web interface?

**Comment by lizutah** [comment]
@kmonson - did this get fixed?

**Comment by kmonson** [comment]
This is not fixed. I'll look into it.

**Comment by kmonson** [comment]
There are limitations as to what I can do to fix this. Opal gives no way to distinguish between input and output files. Right now we use file extensions but there is no guarantee that the user will submit files with those extensions. I will use extensions for now.

A correct fix involves sorting the output files out first and assuming the remainder are input files. If I fix it right I may as well do the gut and re-write or querystatus.py that I've been putting off.
