### ISSUE TITLE
github script to get releases and download numbers

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#207]
Need to turn apbs-pdb2pqr/apbs/tools/github/get Releases.sh into an automatic script.

**Comment by pzli3** [comment]
Uploaded a working copy, but the error handling needs work (when you select --pdb2pqr-1.9.0, it prints PDB2PQR 2.0 still, but prints "no releases here"). Some of the code is roundabout, and there is probably some way to simplify it.

**Comment by lizutah** [comment]
@pzli3 - what's the status of this?  I remember you finishing this and checking it into the repository?

**Comment by pzli3** [comment]
Commited it a few months ago
