### ISSUE TITLE
New APBS electrostatic potential output formats (with multilevel support)

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#21]
@lizutah had several suggestions about new, more compact, formats for output of the electrostatic potential from APBS.

In addition to reducing the output size, we need a multilevel output format which could include information about electrostatic potentials at various resolutions. There is already a data structure available for this in APBS (Vmgrid) but no output format. This would be useful for providing output at various stages of a focusing calculation. In particular, it would allow us to write out multi-resolution dielectric and ionic maps which could be read back in for subsequent calculations.

This data format could, perhaps, be an XML-based generalization of OpenDX with individual OpenDX data files included as CDATA fields. This is a kludge but would make backwards compatibility more straightforward.

This is a modified version of JIRA issue APBS-7.

**Comment by lizutah** [comment]
for the focusing calculation...

**Comment by keith923** [comment]
This is about caching coarse grid calculations to save time when doing e.g., PDB2PKA.

**Comment by sobolevnrm** [comment]
This would be nice to have but is not very urgent.
