### ISSUE TITLE
multigrid documentation broken on web site

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#213]
As reported by @keith923, equations need to be fixed, broken html exists:
http://www.poissonboltzmann.org/docs/elec-calcs/#mgmanual

Please look at this @mchun0630 and @pzli3

**Comment by keith923** [comment]
Also ensure that each option for all mg-* variations opens a description. Finally, ensure that the options for each variation are appropriate.  This may be best done by referring to the old documentation, however ultimately the code may need to be consulted.

**Comment by lizutah** [comment]
@mchun0630 - I think you checked in these changes?  @keith923 please verify that it's fixed (looks good to me)
@mchun0630 - "chgm" didn't expand for me...

**Comment by mchun0630** [comment]
Fixed
