### ISSUE TITLE
fix jmol's colormap

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#217]
Currently the default colormap is blue-white-red, which refers to negative-neutral-positive. Thus the default says blue is negative and red is positive. Nathan said that the default should be set to red-white-blue so that red corresponds with negative and blue with positive.

**Comment by keith923** [comment]
Really?  That's interesting, and surprising.

**Comment by sobolevnrm** [comment]
Red should be negative.  However, I think we need to run some test systems
to confirm the current coloring scheme is incorrect.

**Comment by mchun0630** [comment]
I checked jmol with 1fas and compared it to PMV.
Jmol’s default settings do make blue negative and red positive. 
3Dmol has the default settings at the regular red is negative and blue is positive.

**Comment by lizutah** [comment]
How much work would it be to change the colormap in jmol, @mchun0630 ?

**Comment by lizutah** [comment]
I think @mchun0630 fixed this before she left, anyone remember?

**Comment by karinaliles** [comment]
updated...removed incorrect color scheme (blue-white-red)
