### ISSUE TITLE
Nonlocal PB solver for APBS?

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#228]
Collaborate with Jay Bardhan

**Comment by keith923** [comment]
Jay Bardhan?  This sounds a lot like what I want to do with APBS 2.0, and it's something that we have recently decided was not immediately important.  However, when it does come to light, I think that we want to make sure that what get's implemented meets the criteria of this issue.

**Comment by keith923** [comment]
I've no idea why this is tagged with "boundary elements".  I'm going to remove that, and if someone wants to put it back, they can explain why it belongs.
