### ISSUE TITLE
PDB2PKA graph cut test suite developed

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#231]
@lizutah Can you please assign this to the correct milestone?

**Comment by kmonson** [comment]
I’m working on a test suite right now, but I’m not sure if it’s what Nathan was thinking of. I’m writing something to make it easy to generate graphs to compare sets of results.

**Comment by lizutah** [comment]
@sobolevnrm - is this what you have in mind?

**Comment by sobolevnrm** [comment]
Graphs would be great but I'd also like quantitative comparisons of results
(e.g., absolute differences results between differences) with respect to
fixed cutoff values.

**Comment by kmonson** [comment]
My graph generating code actually did something like that as an
intermediate step before I stripped it out. It would be simple to add it
back in. Using it at the framework for the validation step of a test suite
should be pretty straight forward.

**Comment by kmonson** [comment]
A PDB2PKA test target already exists in the scons scripts. It runs 1a1p and checks the resulting pdb file against a pre-calculated result. This validation step uses the same method to verify normal pdb2pqr runs.

The plan for this:

Add a test to compare the resulting titration curves with a previous known correct result. 

Add a few more small residues to the list of stuff that is checked. We need to be careful as 1a1p already takes several minutes to run.

**Comment by kmonson** [comment]
Going to add more residues to test against then we'll call this done.

**Comment by kmonson** [comment]
Finished in 78d68e9ac8d1cf2a098fe2f9e7d900c426e25e6b.
