### ISSUE TITLE
Merge out-of-source build support into master

### ISSUE THREAD

**Issue by erikjensen** [Electrostatics/apbs-pdb2pqr#233]

**Comment by lizutah** [comment]
Also pull in these requested changes to the makefile if relevant:
https://github.com/Electrostatics/apbs-pdb2pqr/pulls

**Comment by lizutah** [comment]
@erikjensen, how do you handle finding the Eigen library?  cmake isn't finding my install from homebrew.

**Comment by erikjensen** [comment]
@lizutah I didn't make any changes to how Eigen is located. When building, I added `-I/path/to/eigen3` to CMAKE_CXX_FLAGS so the compiler could find it. I could look into trying to make the build a bit smarter about trying to find Eigen, but that should be a separate issue.

**Comment by erikjensen** [comment]
Also, I haven't look over the other pull requests, yet, but I should be able to, tomorrow.

**Comment by lizutah** [comment]
closing this and moving the pull requests to a new issue:
https://github.com/Electrostatics/apbs-pdb2pqr/issues/259
