### ISSUE TITLE
PB-SAM integration into APBS

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#239]
(no individual issues for this yet)

**Comment by keith923** [comment]
I'm thinking that we can assign this to Lisa?

**Comment by lwwilson1** [comment]
@lfelberg I guess we can close this now? It certainly all looks good and works well for me now

**Comment by keith923** [comment]
@lwwilson1 I think I agree.  I'm closing now, and if @lfelberg objects, she can reopen it.
