### ISSUE TITLE
Create ADSETMEAS plugin

### ISSUE THREAD

**Issue by kmonson** [Electrostatics/apbs-pdb2pqr#241]
ADSETMEAS - Auomated Determination of Salt-bridge Energy Terms and Micro Environment from Atomic Structure using APBS version 1.0

**Comment by keith923** [comment]
@kmonson will add more context.  :smile:

**Comment by kmonson** [comment]
[ADSET.pdf](https://github.com/Electrostatics/apbs-pdb2pqr/files/6938/ADSET.pdf)

**Comment by kmonson** [comment]
We need more information from the author. We have a few awk scripts and I don't think we have the complete code for the plug in.

**Comment by keith923** [comment]
Do you want to attach the awk scripts to this issue?  You could also attach, or inline the email that started the issue.

**Comment by keith923** [comment]
Oh!  I missed that PDF.  That's awesome -- thanks!
