### ISSUE TITLE
web site search

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#244]
I think the search bar on our web site should only search for content in the poissonboltzmann domain by default.  Can we fix this so that we don't generate links to our old google site, for example?

Also, the search bar is still finding documents in the old path.  For instance, if you search for "pymol", you get the following result:
http://www.poissonboltzmann.org/apbs-pdb2pqr/docs/calculating/

**Comment by lizutah** [comment]
It looks like the best solution for removing the old web pages is to remove the old branch in the main apbs-pdb2pqr repository.

**Comment by mchun0630** [comment]
Deleted the old pages with the weird purple bg; am still working on search restrictions

**Comment by pzli3** [comment]
Committed to electrostatics.github.io

**Comment by pzli3** [comment]
There's a bug on the end of google custom search...
for example if you search for pymol it lists that there are 3 pages of results, but clicking on the third page redirects to the second page and it now only lists 2 pages of results (there are only two unique pages)
