### ISSUE TITLE
Color discrepancies between jmol/3dmol and pymol

### ISSUE THREAD

**Issue by pzli3** [Electrostatics/apbs-pdb2pqr#245]
![jmol_1](https://cloud.githubusercontent.com/assets/8239038/8063264/9d209462-0e88-11e5-9aec-f221b90117f6.png) Jmol isoval from -1 to 1

![pymol1](https://cloud.githubusercontent.com/assets/8239038/8063419/68402fe0-0e89-11e5-90c1-ee21d3b20b68.png) pymol isoval from -1 to 1

![3dmol1](https://cloud.githubusercontent.com/assets/8239038/8063503/e1c0a070-0e89-11e5-9eff-c713a2277d33.png) 3dmol isoval from -1 to 1

Jmol and 3Dmol look very similar (almost exactly the same) because they are generated from the same dx, but the dx generated from APBS tools in PyMol produces different results (last updated 2009).

**Comment by lizutah** [comment]
I think @mchun0630 fixed this before she left?
