### ISSUE TITLE
BEM - fortran translation to C

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#251]

**Comment by keith923** [comment]
This work was begun by Rachael Keller.  We need to locate her code and put it into a branch, or a separate repository.

Additionally, while she was doing the work, she had a question for Weihua.  He responded with some excellent references, as well as a potential starting point for a C port of the code.  Below are the salient points:

*  The reference can be downloaded from http://faculty.smu.edu/wgeng/research/GengKrasny_JCP_2013.pdf
* A standalone boundary element TABI solver, you can get the code from http://sourceforge.net/p/tabipb/code/ci/master/tree/
* We would need to contact him to obtain the C version he has of the boundary element Poisson-Boltzmann solver (without the Treecode acceleration but everything else).

**Comment by lizutah** [comment]
Rachael's code is here: smb://PNLFS12/Electrostatics/code/BEM_c/

**Comment by lizutah** [comment]
@Jiahuic replaced the fortran code with latest version.
