### ISSUE TITLE
BEM - better mesh support

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#253]

**Comment by keith923** [comment]
@sobolevnrm  had this in the APBS 3.5 release milestone.  The duplicate issue was part of BEM APBS release milestone.  I attempted to add BEM, but it changed it to BEM.  I guess it makes sense that you can't have an issue in two different milestones.  I'm not sure where it should really end up, so I'm just going to leave it alone.

**Comment by lizutah** [comment]
duplicate of #374.  Closing.
