### ISSUE TITLE
mailing list: PDB2PQR not implementing modified FF

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#26]
On Wed, Apr 2, 2014 at 11:09 AM, Che Martin <che.l.martin@gmail.com> wrote:

    Good afternoon,

    I am a new user. When I try to generate a pqr file from my attached pbd which contains a phosphorylated Thr (Res 82). The resulting pqr does not contain my phosphorylated residue. I read the mailing list and they mentioned that I should use a modified force field. So I added the phosphate group to my FF file (attached) however the pqr file still comes back missing the modified Thr82 residue and contains a remarked section:

    Please advise, am I using the wrong force-field file?

    Thank you,
    Che
    *****************************************************************************************

    REMARK   5 WARNING: PDB2PQR was unable to assign charges
    REMARK   5          to the following atoms (omitted below):
    REMARK   5              63 O in THR 18
    REMARK   5              152 O in THR 24
    REMARK   5              630 O in THR 56
    REMARK   5              716 O in THR 63
    REMARK   5              819 O in THR 71
    REMARK   5              992 P1 in TPO 82
    REMARK   5              993 O1 in TPO 82
    REMARK   5              994 O2 in TPO 82
    REMARK   5              995 O3 in TPO 82
    REMARK   5              1244 O in THR 98
    REMARK   5 This is usually due to the fact that this residue is not
    REMARK   5 an amino acid or nucleic acid; or, there are no parameters
    REMARK   5 available for the specific protonation state of this
    REMARK   5 residue in the selected forcefield.
    REMARK   5
    REMARK   5 WARNING: Non-integral net charges were found in
    REMARK   5          the following residues:
    REMARK   5              THR A 18 - Residue Charge: 0.5100
    REMARK   5              THR A 24 - Residue Charge: 0.5100
    REMARK   5              THR A 56 - Residue Charge: 0.5100
    REMARK   5              THR A 63 - Residue Charge: 0.5100
    REMARK   5              THR A 71 - Residue Charge: 0.5100
    REMARK   5              TPO A 82 - Residue Charge: -0.4300
    REMARK   5              THR A 98 - Residue Charge: 0.5100

    **********************************************************************************************

**Comment by kmonson** [comment]
I believe I already helped this person via the mailing list.
