### ISSUE TITLE
Recreate lost images for examples page

### ISSUE THREAD

**Issue by mchun0630** [Electrostatics/apbs-pdb2pqr#260]
http://www.poissonboltzmann.org/examples/running_apbs_through_pdb2pqr_web_portal/ 's images are linking to the deleted branch, gh-pages, and so the images aren't showing up.

**Comment by lizutah** [comment]
I think you just need to update the link?  It looks like the images are in the img directory.
- liz

**Comment by mchun0630** [comment]
Yep, I saw apbs-pdb2pqr/blob/gh-pages/img/Picture2.png?raw=true and panicked for a second. I'll put the images in.

**Comment by mchun0630** [comment]
Fixed img src links
