### ISSUE TITLE
geoflow parameters to expose?

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#262]
what parameters do we need to expose in the geoflow code.  Most are hard coded currently, but the api allows for modifications.
(see @keith923 's email subject "Geometric flow input file parameters")

**Comment by sobolevnrm** [comment]
Can you provide a list here?

**Comment by lizutah** [comment]
An over complete list (missing related follow-up, which requires digging in the code):
[] lpbe:  Is ionic strength actually used in these calculations?  If not, we need to change this keyword.
[] bcfl: How are boundary conditions calculated in geometric flow?  This will change the behavior of this keyword.
[] srfm: Please delete this keyword.
[] swin: Please delete this keyword.
[] dcel: Please change this to “grid” for consistency with http://www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/elec-input-file-section/elec-keywords/grid
[] glen: We’re missing this important parameter (www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/elec-input-file-section/elec-keywords/glen) which makes me worried that it is hard-coded somewhere.  Can you check?
[] dime: We’re missing this important parameter (http://www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/elec-input-file-section/elec-keywords/dime) which makes me worried that it is hard-coded somewhere.  Can you check?
[] pres: Please change this to “press” for consistency with http://www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/apolar-input-file-section/apolar-keywords/press
[] gama: Please change this to “gamma” for consistency with http://www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/apolar-input-file-section/apolar-keywords/gamma
[] vdw: What does this keyword do?  My guess is that it is the same as our “bconc” (http://www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/apolar-input-file-section/apolar-keywords/bconc) but I’m not sure.
[] etol: It would be nice to have a keyword like this (http://www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/elec-input-file-section/elec-keywords/etol), particularly since it must be hard-coded somewhere...
[] ion:  Based on the absence of this keyword (http://www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/elec-input-file-section/elec-keywords/ion), I think we are not actually solving the LPBE
[] write:  It would be good to have something like this (http://www.poissonboltzmann.org/apbs/user-guide/running-apbs/input-files/elec-input-file-section/elec-keywords/write)

**Comment by sobolevnrm** [comment]
We should remove "lpbe" from this list and create a new issue requesting linearized PB support for geoflow.

**Comment by sobolevnrm** [comment]
Ideally, "bcfl" should be included in geoflow -- I have no idea what boundary conditions it uses currently.

**Comment by lizutah** [comment]
@sobolevnrm - "glen" is calculated by taking a bounding box around the atoms, padded by "p_extvalue" and divided by grid (dcel).  Would you like to expose the padding for the user to change or implement a new way of creating the grid?  @keith923 - how is this currently done in APBS?

**Comment by sobolevnrm** [comment]
I think it would be better just to expose glen rather than a separate
p_extvalue.  That's the way it's done in APBS.

**Comment by lizutah** [comment]
Closing.  All the parameters above have either been exposed or moved to new issues for implementation.  Comments (above) have also been added (in bold) for most options.
