### ISSUE TITLE
Art image

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#263]
Generate an image from PDB2PQR/APBS for an art installation at PNNL.  (6/26 deadline)

**Comment by mchun0630** [comment]
does this mean the 3dmol.js viewer website?

**Comment by lizutah** [comment]
or pymol.  Which ever tool makes the best image.  The 3dmol is nice because it's new and easily accessible.
@sobolevnrm can maybe suggest a dataset?

**Comment by mchun0630** [comment]
VMD works too, if all you want is a protein visualization. Do you want the electrostatic potential mapped out too?

**Comment by keith923** [comment]
A Death Star easter-egg would be awesome.

**Comment by mchun0630** [comment]
![1fas_cartoon](https://cloud.githubusercontent.com/assets/7968528/8379145/e5c0a0ac-1bd2-11e5-8c5c-0015985e0069.png)
![1fas_sas](https://cloud.githubusercontent.com/assets/7968528/8379146/e9351e2a-1bd2-11e5-8770-25362eda2116.png)
![1fas_vmd](https://cloud.githubusercontent.com/assets/7968528/8379149/eb520452-1bd2-11e5-9531-9780613713a8.png)

**Comment by mchun0630** [comment]
Is this something like you were looking for?
The first two are from 3Dmol.js, the last is VMD

**Comment by mchun0630** [comment]
![1fas_deathstar](https://cloud.githubusercontent.com/assets/7968528/8382604/9899b500-1be8-11e5-84f7-38120cbd6cc7.png)
This is Keith's recommended version of 1FAS

**Comment by mchun0630** [comment]
hint: bottom right

**Comment by sobolevnrm** [comment]
Field lines look cool!

**Comment by keith923** [comment]
Plus there is an Easter Egg!!!!  Thanks to Minju's awesomeness.

- Keith

On Jun 26, 2015, at 16:25, Nathan Baker <notifications@github.com<mailto:notifications@github.com>> wrote:

Field lines look cool!

**Comment by lizutah** [comment]
Agree on the field line images.  This image good to pass along for the gallery, @sobolevnrm ?

**Comment by sobolevnrm** [comment]
Yes, thanks!

**Comment by lizutah** [comment]
Submitted to Karen by Minju.  Closing.
