### ISSUE TITLE
Integrate AESOP framework into PDB2PQR

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#27]
@kmonson 

The code is from Dimitri Morikis' group and can be downloaded from http://biomodel.engr.ucr.edu/aesop-1.0.0.zip

**Comment by neilav** [comment]
I'd be happy to re-implement the R code into python. I could perhaps create a module in the extensions directory of apbs2pqr?

**Comment by sobolevnrm** [comment]
Yes, that would be very helpful!  You were referring to the extensions directory of PDB2PQR, right?

**Comment by neilav** [comment]
Yes I was :)

**Comment by sobolevnrm** [comment]
Closing.  Will reopen if extension provided.
