### ISSUE TITLE
APBS builidable test suite

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#271]
add build option to APBS to build test suite

**Comment by lizutah** [comment]
@sobolevnrm - do you mean to just run apbs-pdb2pqr/apbs/tests?

**Comment by keith923** [comment]
These tests are running as part of the Travis CI process that runs whenever the master branch is updated.  I'm going to close this issue assuming that what we have is sufficient for what was required.

**Comment by lizutah** [comment]
Except that the build is failing.  Are all the issues with the build failing documented on github?
https://github.com/Electrostatics/apbs-pdb2pqr/issues/364

**Comment by keith923** [comment]
But, the tests are passing!  Ironically enough.
Yes, that's the only (current) problem with the build.  It's not a problem with APBS proper, but an ancillary program, that isn't part of the tests. Sadly, we only test the main executable. Sounds like we need another issue...?
