### ISSUE TITLE
APBS web interface release

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#279]
@sobolevnrm - what does this consist of (that may not be done already)?

**Comment by sobolevnrm** [comment]
Probably what Karina/Peter/Minju have done covers most of it but we should review the new interface at one of our meetings before closing this issue. 

--
Nathan Baker

**Comment by sobolevnrm** [comment]
@lizutah - can you add this to one of our meeting agendas?

**Comment by lizutah** [comment]
Closing this.  I'm 99% sure we reviewed this, and found changes and fixed them but I don't remember them now.
