### ISSUE TITLE
improved pKa: slow PDB2PKA integration

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#294]
@sobolevnrm - more info here?

**Comment by lizutah** [comment]
@sobolevnrm - pinging you again on this issue.

**Comment by sobolevnrm** [comment]
This is just making the old Monte-Carlo-based PDB2PKA available through the PDB2PQR web interface.

**Comment by lizutah** [comment]
@kmonson - can you comment on this?

**Comment by sobolevnrm** [comment]
@kmonson, monson, anyone? Please respond.

**Comment by kmonson** [comment]
This was released in 2.0. You can choose between PROPKA and PDB2PKA via the web interface.
