### ISSUE TITLE
Makefile fixes for new Geoflow version in APBS

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#308]
Need to merge current makefile, which builds the standalone geoflow code, into the makefile for APBS.  Need to discuss with APBS cmake guru, @erikjensen.

**Comment by keith923** [comment]
You may want to considering merging my branch before you sit down with @erikjensen.

**Comment by lizutah** [comment]
Yes.  Thanks for the reminder.

**Comment by keith923** [comment]
Hey @lizutah.  If you like, I can do this at the same time that I'm integrating the FETK and MALOC external repos.

**Comment by lizutah** [comment]
@keith923 - see the geoflow-merge branch.  cmakelists.txt was changed to build the geoflow libraries but not set GEOFLOW_ENABLE to ON.  Just need to build the library and then I can go in and modify the calls to the solver.

**Comment by keith923** [comment]
Should be good to go Liz.

**Comment by lizutah** [comment]
This is working now.  Had to enable includes for APBS in the standalone directory:
https://github.com/Electrostatics/geoflow_c/commit/ffc65e63074d929fab3749d7516b72a421bd0ed0
and tell APBS to build with new flags:
https://github.com/Electrostatics/apbs-pdb2pqr/commit/670baf3376034e712ddc2d9f2b38067d4515f0cd
