### ISSUE TITLE
Add load 3dmol functionality to 3dmol web viewer

### ISSUE THREAD

**Issue by karinaliles** [Electrostatics/apbs-pdb2pqr#318]
Allow user to upload .3dmol file that recreates the protein; contains .pqr and .dx file (or .cube file); upload via file dialog or drag and drop

**Comment by lizutah** [comment]
Is this feature available in our implementation of jmol?

**Comment by karinaliles** [comment]
Yes, this is a jmol feature that has not been implemented in 3dmol yet. In Jmol a .Jmol ZIP file is loaded and recreates the protein; contains .pqr and APBS.dx file; the user can upload using file dialog or drag and drop. The .Jmol file is saved from the tool's save functionality.
