### ISSUE TITLE
Add save 3dmol functionality to 3dmol web viewer

### ISSUE THREAD

**Issue by karinaliles** [Electrostatics/apbs-pdb2pqr#319]
Allow user to save .3dmol file that recreates the protein; contains .pqr and .dx file (or .cube file); to be later uploaded

**Comment by lizutah** [comment]
Is this available in the jmol implementation currently?

**Comment by karinaliles** [comment]
Yes, this is a jmol feature that has not been implemented in 3dmol yet. It saves the .pqr and APBS.dx files to recreate the protein and saved state; any remote files must also be saved locally
