### ISSUE TITLE
Add Binary DX support to tools/mesh/dxmath

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#323]
Now that APBS supports the binary dx file format we should add that support to dxmath.

**Comment by lwwilson1** [comment]
Just dxmath, or also the related tools like analysis.c? What about utilities analagous to del2dx, dx2mol, mergedx, etc.?

**Comment by keith923** [comment]
I think all of the tools that read or write DX files should be updated.

**Comment by lwwilson1** [comment]
dxmath and the utilities now support binary dx files. I still plan on doing a little bit of output formatting and cleaning up some of these utility codes. I'm going to open a new issue for mergedx2.c, which will take a bit more elbow grease.
