### ISSUE TITLE
3Dmol.js incorrect Color scheme

### ISSUE THREAD

**Issue by mchun0630** [Electrostatics/apbs-pdb2pqr#325]
The color scheme for "blue-white-red" is emulated as "purple-blue-green" instead of what it should be (blue negative, white neutral, red positive).  
![fssdfdsfsdfdsfdsfdsfdsfdshgshsegsehsha](https://cloud.githubusercontent.com/assets/7968528/9229604/c4ffcabc-40d2-11e5-9d04-e6e50328cbf8.png)

**Comment by karinaliles** [comment]
removed incorrect color scheme
