### ISSUE TITLE
Nathan translate PB-SAM workflow

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#326]
@keith923 add comments here.

**Comment by keith923** [comment]
https://bitbucket.org/lfelberg/pbsam/src/056861068c702f9d77e2a1d0e925134505b29f8a/PBSAM_guide.pdf?at=master

**Comment by sobolevnrm** [comment]
Where can I find the example files?  They're not in this directory and the PDF doesn't contain any details about the parameters for the electrostatic calcualtions.

**Comment by lizutah** [comment]
Examples:
https://github.com/Electrostatics/PB-SAM/tree/master/test
Documentation:
https://github.com/Electrostatics/PB-AM/tree/master/docs
