### ISSUE TITLE
Sphere Discretization

### ISSUE THREAD

**Issue by kozlac** [Electrostatics/apbs-pdb2pqr#327]
Need to translate Maria's Sphere Discretization code from python to C (and integrate into vacc.c ?).

**Comment by sobolevnrm** [comment]
Or rewrite it with this in mind:
https://en.wikipedia.org/wiki/Geodesic_grid

It also relates to spherical designs, do you know anyone who knows about
those?

**Comment by kozlac** [comment]
Well...Katy knows about designs but I am not sure if she has worked with this kind. I recall that one of the professors at Iowa State area of research was on discrete geometry. He is a very helpful and active guy, I could ask him if he has any resources on this.
