### ISSUE TITLE
3Dmol Browser Issues General

### ISSUE THREAD

**Issue by mchun0630** [Electrostatics/apbs-pdb2pqr#328]
General Issues with 3Dmol evident in all browsers (Safari, IE, Chrome, Opera, Firefox:

•	Opaque button doesn’t work unless you switch the button back and forth instead of on the first try. 

•	The show/hide buttons also have glitch in which the white square on the buttons highlights blue, and then moves jaggedly to show “hide”

•	There are no real “consistent” bugs, but a group of bugs (e.g. going extreme values and trying to reset doesn’t work, switching between color scheme is laggy or rendered the wrong color scheme) were present or not present in all the browsers, depending on the trial. 

•	Electrostatic potential maps correctly with SAS, but VDW and SES have the patchy, incorrect emulation

•	When resetting values the sliders don’t return back to normal.

Note* Usually refreshing cleared some big problems, like incorrect representation of color scheme, but sometimes it just cleared the “current” problems but made new ones.

For more reference view comments in Issue #324

**Comment by karinaliles** [comment]
All noted issues work. Issues may have been resolved from previous code fixes
