### ISSUE TITLE
Update examples/*/README.html to markdown

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#335]
The README files in the examples document the results that APBS has had over many, many versions.  It would be great if they were in markdown so that viewing them here on GitHub were trivial.

**Comment by mchun0630** [comment]
Should I delete the existing HTML files, or should I keep them?

**Comment by sobolevnrm** [comment]
I'd delete them.  Did you update all of the links between documents?

**Comment by mchun0630** [comment]
I think so. The only link that didn't work was the apbs sourceforge/docs, I changed that to http://sourceforge.net/projects/apbs/; Is this okay? Or would it be better to link to the poissonboltzmann website?

**Comment by sobolevnrm** [comment]
Poissonboltmann.org would be better. Thanks!

**Comment by mchun0630** [comment]
Updated the website links and replaced the html files with markdown!
