### ISSUE TITLE
Linux FETK build MALOC link problem

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#336]
The linux FETK build is failing with the following when the binary is run:
`apbs: error while loading shared libraries: libmaloc.so.1: cannot open shared object file: No such file or directory`
I'm not sure why this isn't happening on OS X.

**Comment by keith923** [comment]
Just a quick status update.  I have tried passing `--enable-static`, as well as other things, to the configure script that we call via CMake.  Nothing seems to make a difference.  However, when running configure by hand, it seems to default to creating a static library.  Grrr.  Not sure what's going on, but I stopped messing with it in favor of working on the MPI library linking, which I'm hoping to have better luck with.  I'll hit this again later.

**Comment by sobolevnrm** [comment]
I was talking to some developers who manage very large codes at other labs
and they've ditched autoconf and Cmake completely in favor of extensive
README.md files and GNU Make.

**Comment by keith923** [comment]
So they have basically reverted to the way that we used to do it 20 years ago?  I'd love to hear about their experiences that led them down that path.

In any case, GNU Make doth not work upon Windows.  Can we ditch Windows?  :laughing:

**Comment by lizutah** [comment]
A simple fix for the shared libs is just setting the LD_LIBRARY_PATH, so let's document that, fix it for Travis CI, and push this into the backlog for now.

**Comment by sobolevnrm** [comment]
:)

**Comment by keith923** [comment]
Where do we document setting LD_LIBRARY_PATH?
I updated the Travis CI script to do this.  It's working, but there is another problem that is documented in issue #364.

**Comment by lizutah** [comment]
https://github.com/Electrostatics/apbs-pdb2pqr/blob/master/apbs/README.md would be fine for documenting the build/run process, unless we have a different file with this info?  

Here is suggestion for a README format we could follow:
https://github.com/SCIInstitute/SCI-Solver_FEM
