### ISSUE TITLE
Missing README files for APBS

### ISSUE THREAD

**Issue by mchun0630** [Electrostatics/apbs-pdb2pqr#340]
The folders:
-smpbe
-membrane
-bem
-geoflow

Have no README files. The misc folder has a README file, but it is very sparse.

**Comment by keith923** [comment]
Additionally the README in the root examples directory has links that are busted, and to html files.  And several of the subdirectories have mis-named README.md files that don't display by default when landing in the directory on GitHub.

To bad there aren't any interns left to help fix this mess.

**Comment by lizutah** [comment]
The tables are fixed and the README links are fixed, but there's a link that needs to be added to fix, to point to a FAQ (#403).  Still need to add the missing READMEs.

**Comment by lizutah** [comment]
The current examples/README is now cleaned up, with fixed tables and working links, However, some work remains.  

To summarize...
* the following dirs need readmes:
*    smpbe, membrane, bem, and geoflow (@lizutah)
*The following directories need to be included in the main example readme table:
*   pka-lig/UHBD, opal, and misc

**Comment by kozlac** [comment]
I added the readme files to smpbe, membrane, and bem. @lizutah  already had one for geoflow. The readme's for smpbe and bem probably need previous versions' results. 

@lizutah Should this folders also be included in the main example readme table?

**Comment by lizutah** [comment]
Yes, please add them to the main table.

**Comment by kozlac** [comment]
Added all the missing readme files and the missing folder to the main example's table. Also, I fixed the opal/ readme file table and converted the misc README to a md file. @lizutah, can we close this one? Or do you know of any other changes needed to be made?

**Comment by lizutah** [comment]
Looks good.  Closing.
