### ISSUE TITLE
Outdated link to web server on http://www.poissonboltzmann.org/examples/comp_tut/

### ISSUE THREAD

**Issue by kmonson** [Electrostatics/apbs-pdb2pqr#341]
It still links to http://nbcr-222.ucsd.edu/pdb2pqr_1.9.0/

We should change it to http://nbcr-222.ucsd.edu/pdb2pqr so it redirects to the current version.

**Comment by lizutah** [comment]
fixed.  pointed to "getting structures ready" page.
