### ISSUE TITLE
More informative error message for CNT atoms

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#344]
Hi Kyle --

Can we please make this error message more informative?

Thanks,

--
Nathan Baker
Laboratory Fellow
Computational and Statistical Analytics Division
Pacific Northwest National Laboratory
+1-509-375-3997
https://goo.gl/H3X8f1

Begin forwarded message:

From: "Baker, Nathan" <Nathan.Baker@pnnl.gov>
Subject: Re: PDB2PQR: urgent technical query
Date: September 21, 2015 at 06:04:05 PDT
To: Neelanjana Sengupta <n.sengupta@ncl.res.in>
Cc: Asiskumar jana <ak.jana@ncl.res.in>, "Monson, Kyle E" <Kyle.Monson@pnnl.gov>, "Jurrus, Elizabeth R" <Elizabeth.Jurrus@pnnl.gov>

Hello --

You will not be able to parameterize your CNT with PDB2PQR because it does not have parameters for the CNT atoms -- that is what the obscure error message is trying to communicate.  You will need to construct the PQR file manually by adding the charge and radius your PDB file as described here:  http://www.poissonboltzmann.org/docs/file-format-info/

Sincerely,

--
Nathan Baker
Laboratory Fellow
Computational and Statistical Analytics Division
Pacific Northwest National Laboratory
+1-509-375-3997
https://goo.gl/H3X8f1

On Sep 20, 2015, at 20:50, Neelanjana Sengupta <n.sengupta@ncl.res.in> wrote:

Dear Nathan,

I had requested for Subscription to the mailing list two days back. Since I haven't been accepted yet, and as this request is very urgent (required for a paper revision), I am writing to you directly. Would appreciate your help very much. My graduate student, Asis, is copied on the email.

We are trying to calculate binding free energy of a protein with a carbon nanotube (CNT) using APBS and PDB2PQR. For CNT, carbon atoms are modelled as uncharged Lennard- Jones particles using aromatic SP2 carbon atoms of the CHARMM force field. Our topology file was thus build manually. But, we are not able to generate PQR file from pdb, for CNT using PDB2PQR with CHARMM package. Errors are shown below :

Traceback (most recent call last):
  File "/usr/share/pdb2pqr/pdb2pqr.py", line 65, in <module>
    mainCommand(sys.argv)
  File "/usr/share/pdb2pqr/main.py", line 619, in mainCommand
    ffout = options.ffout)
  File "/usr/share/pdb2pqr/main.py", line 284, in runPDB2PQR
    myRoutines.findMissingHeavy()
  File "/usr/share/pdb2pqr/src/routines.py", line 614, in findMissingHeavy
    raise ValueError, "No heavy atoms found!"
ValueError: No heavy atoms found!

I am attaching the PSF and PDB file of the CNT. Could you suggest ways to get around this problem?

Thanks  a lot.

Best regards,
Neelanjana

Neelanjana Sengupta, PhD
Scientist, Physical Chemistry Division
and
Assistant Professor, AcSIR
CSIR-National Chemical Laboratory
Dr. Homi Bhaba Road
Pune 411008, India
Phone: +91-20-2590 2087
Fax: +91-20-2590 2636
Website: 
http://academic.ncl.res.in/n.sengupta

Disclaimer:

This message and the information contained herein is proprietary and confidential and subject to the policy statement of the National Chemical Laboratory, Pune, India. You may review the policy at http://www.ncl-india.org/files/TermsAndConditions/WebmailDisclamer.aspx

**Comment by kmonson** [comment]
eee4a75324cbc3ae14813419dfd98bc348e99194
