### ISSUE TITLE
update registration link

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#345]
See electrostatics/electrostatics.github.io#24.

**Comment by lizutah** [comment]
@sobolevnrm - do we want to add a link to the registration on the pdb2pqr web page?  Doesn't appear we have linked this in the past.

**Comment by sobolevnrm** [comment]
Yes, that's a great idea!

**Comment by lizutah** [comment]
fixed in 4f4f064f5f33c2447c603bb67ebcbb9e651d9423
