### ISSUE TITLE
Server Can't Find Download Files in the Protein-RNA Tutorial Page

### ISSUE THREAD

**Issue by kozlac** [Electrostatics/apbs-pdb2pqr#348]
In the Protein-RNA tutorial page < http://www.poissonboltzmann.org/examples/Protein-Rna_Tutorial/#elec> there are instructions to download various scripts. These links are down and the error says that the server can't find the files. The contents of the scripts though are being shown and it could be just cut and pasted but the instructions would have to be changed. @lizutah said will look into this.

**Comment by lizutah** [comment]
Fixed with https://github.com/Electrostatics/electrostatics.github.io/commit/5be35491ec2083c30b948f6c044e2ea736087718.
