### ISSUE TITLE
Linux libc woes

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#351]
For the 1.4.1 release, we built Linux binaries that were built on a new-at-the-time version of Ubuntu.  This wreaked havoc with some users that are still running CentOS 5, or something similarly old.  The problem stems from us linking to a too-new version of libc, that is not backwards compatible with older versions.

We need to decide how far back we want to go (CentOS 5?) support-wise, and build the Linux binary on that version of the OS.

**Comment by keith923** [comment]
Let's pick a version of libc that's a major release in the last year or two, and support that.  If a user is using something older, then they can build from source.

**Comment by kozlac** [comment]
@keith923  According to [distrowatch](http://distrowatch.com/table.php?distribution=centos) CentOS versions have the following glibc library versions as default:

|CentOS Version |glibc Version|
|-----------------------|-----------------|
|7.1-1503              | 2.17            |
|6.6                       | 2.12            |
|5.11                     | 2.5              |
|4.9                       | 2.3.4           |
|3.9                       | 2.3.2           |
|2.0                       | 2.2.4           |

I know that "in general" libraries are forward compatible but not the other way around. Do you want to pick the one for CentOS 5 and supports that one? Or, choose and older one a hopefully everything works?

Also, when building the binary, what should I enable? (e.g. FeTk, Tinker, etc...)

**Comment by kozlac** [comment]
The binary is build and I tested it with a couple of .in files and seems to be working. I am having problems though building with BUILD_DOC on. For whatever reason the pdf gets written and then a make error occurs. As per @keith923 advice, we can take the doc folder from a build in another computer. For now I am sitting on this one.

**Comment by kozlac** [comment]
Waiting for realease 1.4.2 to close this issue.

**Comment by kozlac** [comment]
Trying to build APBS with geoflow enabled in CentOS 5 is failing because the default gcc version is 4.1.2 which does not support -std=c++11 necessary for the build. I could upgrade the gcc version, however, I don't know how the libraries are being link (e.g dynamically or not) in which case it may or may not run in a standard installation of CentOS 5. I will upgrade the gcc, build the binary, and test it in a fresh CentOS install to see if it runs.

**Comment by kozlac** [comment]
Decision was made not to support the old libc and move on.
