### ISSUE TITLE
replace MSMS in BEM

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#374]
Currently, the BEM implementation calls a binary version of MSMS (http://mgl.scripps.edu/people/sanner/html/msms_home.html).  What do we replace it with?

**Comment by lizutah** [comment]
@lwwilson1 says to replace with nanoshaper, but provide option in case msms is already installed.

**Comment by keith923** [comment]
Do we want to invest the time to do this?

**Comment by sobolevnrm** [comment]
It would be great if we could add support for it.

**Comment by lizutah** [comment]
@lwwilson1 - can you update this issue?

**Comment by lwwilson1** [comment]
NanoShaper, both Skin and SES support, is available for Mac and Linux, assuming the user has the NanoShaper executable installed in their path. CMaking the project gives Mac, Linux, and Windows users the proper executables in the build/bin that they can install. I was waiting to close this issue until I get dylibs/dlls working for Mac, Linux and Windows so I can remove all system calls from TABI-PB.

**Comment by lizutah** [comment]
closing.  Just needs to build on windows.  see issue #453
