### ISSUE TITLE
pdb2pqr does not apply most pdb2pka results to 1jhg 

### ISSUE THREAD

**Issue by kmonson** [Electrostatics/apbs-pdb2pqr#380]
Running pdb2pka on 1jhg result in the following message at the end of the run:

Applying pKa values at a pH of 7.00:
{'ARG 15 A': 7.917926694068141,
 'ARG 21 A': 8.131114949660171,
 'ARG 48 A': 8.03743168834728,
 'ARG 54 A': 8.35100937486867,
 'ARG 63 A': 10.312631538711198,
 'ARG 69 A': 8.156864573405615,
 'ARG 97 A': 9.686704484517373,
 'ASP 108 A': 3.8991716736163093,
 'ASP 24 A': 2.1979788359253116,
 'ASP 33 A': 2.809122975636334,
 'ASP 46 A': 2.1147591990814814,
 'C- 108 A': 2.3488765032555285,
 'GLU 101 A': 4.9382742922420775,
 'GLU 102 A': 2.746194230053372,
 'GLU 13 A': 4.539979934153146,
 'GLU 18 A': 2.506273338069902,
 'GLU 47 A': 1.7436924453860514,
 'GLU 49 A': 3.1312129635430943,
 'GLU 59 A': 2.921354629995028,
 'GLU 60 A': 0.33972047254607013,
 'GLU 65 A': 3.670377904788012,
 'GLU 70 A': 2.205362760782576,
 'GLU 74 A': 6.5184867867594605,
 'GLU 95 A': 2.001001852608849,
 'HIS 16 A': 3.413407745615523,
 'HIS 35 A': 3.4325654721597902,
 'LYS 106 A': 7.480009991290344,
 'LYS 27 A': 6.976599008350444,
 'LYS 72 A': 5.725555067707227,
 'LYS 90 A': 6.034732641876908,
 'N+ 8 A': 4.167640741085184,
 'TYR 30 A': 5.560939832415442}

```
     PDB2PQR could not identify the following residues
     and residue numbers as returned by PROPKA or PDB2PKA:

         GLU 59 A
         TYR 30 A
         GLU 65 A
         ARG 48 A
         ASP 46 A
         GLU 95 A
         GLU 49 A
         LYS 106 A
         HIS 16 A
         HIS 35 A
         ARG 63 A
         ARG 69 A
         GLU 70 A
         ARG 54 A
         LYS 72 A
         GLU 101 A
         GLU 60 A
         ARG 21 A
         ASP 33 A
         C- 108 A
         ASP 24 A
         GLU 74 A
         ARG 15 A
         GLU 18 A
         GLU 47 A
         ASP 108 A
         LYS 27 A
         GLU 102 A
         LYS 90 A
         GLU 13 A
         ARG 97 A
         N+ 8 A
```

Repo:

python pdb2pqr.py --verbose --ph-calc-method=pdb2pka --ff=parse --pdb2pka-out=pdb2pka_1jhg 1jhg 1jhg.pqr

**Comment by kmonson** [comment]
The underlying problem is the how chain IDs are assigned combined with our removal of HETATMs before pdb2pka runs. Normally all of the above residues would end up in chain ID "B" but because we remove the entire second chain by removing the HETATMs the chain ID that comes out of pdb2pka is "A" instead of "B". (Yes, it letters it backward.)

This problem does not affect PROPKA. We do not remove HETATMs from the PROPKA input.

The fix for #373 seems to be at least part of the problem.

**Comment by sobolevnrm** [comment]
This doesn't seem to have anything to do with HETATMs....

Check out the multiple occupancies in the PDB file; e.g., around atom 1599:

> ATOM   1599 HH11AARG A  97       3.037  -0.493 -22.487  0.50 55.22           H  
> ATOM   1600 HH11BARG A  97      -2.622   2.084 -21.880  0.50 70.86           H  
> ATOM   1601 HH12AARG A  97       4.314  -0.084 -21.838  0.50 55.22           H  
> ATOM   1602 HH12BARG A  97      -2.420   2.744 -23.200  0.50 70.86           H  
> ATOM   1603 HH21AARG A  97       3.041   1.898 -19.549  0.50 31.57           H  
> ATOM   1604 HH21BARG A  97      -0.117   0.703 -24.372  0.50 67.69           H  
> ATOM   1605 HH22AARG A  97       4.313   1.343 -20.089  0.50 31.57           H  
> ATOM   1606 HH22BARG A  97      -0.919   1.917 -24.692  0.50 67.69           H  

I thought we fixed this a really long time ago!

For the purposes of the paper, delete all of the "B" occupancy states and run the code.

After that's done, we should fix this with high priority...

**Comment by sobolevnrm** [comment]
:poop:

**Comment by kmonson** [comment]
How did you get from chain ID mismatch to a multiple occupancy problem?

**Comment by kmonson** [comment]
Currently pdb2pqr handles multiple occupancy by ignoring every occupancy after the first. In the case of 1jhg you see this in the pqr file:

REMARK   5 WARNING: multiple occupancies found in GLU A 13,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in GLN A 14,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in LYS A 27,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in ASN A 28,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in GLN A 31,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in LEU A 36,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in LEU A 41,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in GLU A 47,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in ARG A 56,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in ARG A 63,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in MET A 66,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in SER A 88,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in GLU A 95,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in ARG A 97,
REMARK   5          at least one of the instances is being ignored.
REMARK   5 WARNING: multiple occupancies found in VAL A 103,
REMARK   5          at least one of the instances is being ignored.

**Comment by kmonson** [comment]
My explanation of the problem above was insufficient.

In the specific case of 1JHG deleting the HETATMs causes the chain ID mismatch. This is probably because of the TER record in the middle of chain A. Deleting HETATMs in general is not the cause of the problem.

Deleting all the HETATMs in 1JHG completely deletes the second chain. Because pdb2pka is still aware of the second chain combined with how with assign chain IDs in this case there results in a mismatch.

**Comment by sobolevnrm** [comment]
There is no second chain in this example.  The TRP residue is a ligand and
is correctly labeled as a HETATM.

**Comment by kmonson** [comment]
Try running pdb2pqr (no pdb2pka) on it with the --chain argument. pdb2pqr
treats it like two different chains. I think it has something to do with
the TER record at 1801 but I need to look into it.

PROPKA does the same thing.

**Comment by sobolevnrm** [comment]
There is only one chain present.  Everything else is a HETATM (e.g., ligand
or water) -- despite the fact that the HETATM is a tryptophan.

**Comment by kmonson** [comment]
I think our best course of action is to stop removing HETATMs before passing the protein off to pdb2pka. Remove water explicitly (optionally leave them in). Find a different solution to #373 as that will crop back up.

This should wait until after the next release.

Sound like a plan?

**Comment by sobolevnrm** [comment]
What will PDB2PKA do if it encounters a HETATM?  Will it ignore it?

**Comment by kmonson** [comment]
I'm not sure. I'll have to try it.
