### ISSUE TITLE
Re-establish APBS remote invocation via Python

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#381]
There was some cruft in the ENABLE_PYTHON option of the main CMakeLists.txt file that I removed as part of issue #372.  Apparently it was once useful!  From @sobolevnrm:

> It allowed users to run APBS on offsite servers from the command line --
> everything was the same except for the command line options, so it could be
> a drop-in replacement for APBS when used with visualization software like
> VMD or PyMOL.

@sobolevnrm would like it back.  Before just resurrecting the cruft that was there, I would like to understand why it needed to be part of the APBS build at all?  Given what it does, why can't we just make a Python file available that points to the correct servers to allow users to submit jobs?

**Comment by sobolevnrm** [comment]
Yes, a Python file would be much cleaner.  It doesn't need to be part of
the build *except* that there are some compiled dependencies related to
Opal that need to be built.  So it will need to be built somewhere but
doesn't need to be part of the APBS build.

**Comment by keith923** [comment]
Huh.  I didn't notice anything about Opal in the build script.  @kmonson do you know anything about that?  Perhaps we could get this sorted out together?

**Comment by kmonson** [comment]
Sure.

I'll have to look at the script to see what we need to do. We might move
this over to pdb2pqr or make it a separate build target in apbs.
