### ISSUE TITLE
Implement Weighted Jacobi

### ISSUE THREAD

**Issue by kozlac** [Electrostatics/apbs-pdb2pqr#382]
I would like to Implement the wjac (weighted Jacobi) as a smoothing options both in cpu and gpu. Maybe even as a gpu solver instead of multigrid. Do you think this would be useful @sobolevnrm, @lizutah ?

**Comment by sobolevnrm** [comment]
Yes, this is a great idea because it would help with apples-to-apples
comparisons between the implementations.
