### ISSUE TITLE
"slimmer GUI"

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#385]
The 3dmol GUI is a little too "fat."  Can we condense the GUI so it doesn't need to be so large in the viewer?  For instance, move "surface" above the section rather than having it on the left of the surface options.

**Comment by karinaliles** [comment]
Done...Let me know if this is what you wanted or if you were hoping for something else. It doesn't look like I have much control to resize the actual visualization without the image (protein) being cut off.

**Comment by lizutah** [comment]
We need to fix the fonts.  See attached.
<img width="278" alt="screen shot 2015-11-24 at 12 59 53 pm" src="https://cloud.githubusercontent.com/assets/1486218/11380608/f99db326-92ab-11e5-806f-a096df22f2e8.png">

**Comment by karinaliles** [comment]
What browser are you using? It doesn't do that on Chrome or Firefox.

**Comment by lizutah** [comment]
Chrome and Firefox.  @kmonson and @keith923, can you guys please try it as well and let us know if you see the same problem with the font (shown above):
http://pt24098/d3k084/pdb2pqr/visualize.cgi?jobid=14490818889&tool=tool_3dmol

**Comment by karinaliles** [comment]
I found and fixed the problem. I was missing a css file (ui_css.css) in visualize.py. I've adding that file.
