### ISSUE TITLE
IE range sliders

### ISSUE THREAD

**Issue by karinaliles** [Electrostatics/apbs-pdb2pqr#389]
Range sliders don't appear correctly
Range sliders don't work

**Comment by karinaliles** [comment]
So far everything that I have tried is not fixing this. I will continue to investigate.
![image](https://cloud.githubusercontent.com/assets/11194692/11545461/78642662-9915-11e5-8243-fe6a3237a4b2.png)

**Comment by lizutah** [comment]
Ooof.  That's annoying.  If you want someone else to try it on IE let us know.  I don't have a windows machine available.

**Comment by karinaliles** [comment]
Yes if Keith or Kyle could look to see if it's doing the same for them or have any suggestions for fixing that would be great.
