### ISSUE TITLE
remove atom labels in 3dmol

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#391]
When labels are added with user clicks, they are very difficult to remove.  Need a "clear all labels" button.

**Comment by karinaliles** [comment]
Liz - Would you be ok if I completely removed this functionality and open a new issue to add it back sometime after the release? The user will still have the option to add and remove all labels.

**Comment by lizutah** [comment]
This feature is fine for now.  I just wanted to document it.  We don't need to fix it for this first release.

**Comment by karinaliles** [comment]
ok

**Comment by lizutah** [comment]
But we do want to keep it open to be fixed at a later date.  :-)

**Comment by lizutah** [comment]
Issue moved to #393
