### ISSUE TITLE
add/remove atoms labels when protein is clicked

### ISSUE THREAD

**Issue by karinaliles** [Electrostatics/apbs-pdb2pqr#393]
Add functionality to add/remove atom labels when a specific atom is clicked -- currently the functionality to add atom label has been removed until the remove functionality is implemented

**Comment by IsabelaPastorini** [comment]
Someone know how i can get the distance between 2 atoms and put at visualization (in a label maybe)? with a line between, connecting them

**Comment by sobolevnrm** [comment]
Hello --

This question doesn't refer to APBS; you should look at the documentation
for PyMOL or VMD (or whichever software you're using) for the answer to
this question.

Thanks,

Nathan
