### ISSUE TITLE
It would be nice to have PDB2PQR ignore case when parsing arguments

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#395]

**Comment by kmonson** [comment]
Would it be sufficient to allow both all upper and all lower case arguments like we do now with the force field names?

I did it that way so that optparse would automatically list possible arguments with you run with --help and do validation for us and there was still some flexibility.

**Comment by sobolevnrm** [comment]
Yes, that would be great.
