### ISSUE TITLE
PDB2PQR should allow both MC and graphcut

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#397]
We should not have removed the Monte Carlo code from PDB2PKA calculations.  Both graph cut and MC should be supported.  This is particularly important because the graph cut method does not appear to be very stable for large proteins.

**Comment by lizutah** [comment]
@kmonson - where was the last commit that you removed the MC code?

**Comment by kmonson** [comment]
The first major commit was here: cd83476eab3177d3e71a6086452032051a392e72

The remaining bits of MC were removed here: 341d850da283be506c25ff431d92d07dfb23ab3d

**Comment by kmonson** [comment]
I thought of a list of all the stuff needed before we can consider this done:

Add command line option.
Add option to server.html.in. 
Integrate new option into main_cgi.py (OPAL and non OPAL)
Restore MC in interaction energy calculations. (See cd83476)
Restore MC in intrinsic pKa calculations (See 341d850)
Update MC output format to match graphcut output format.
Add tests to "scons/scons.py pdb2pka-test"

**Comment by lizutah** [comment]
@kmonson, but the MC code is still in the paper and paper_unplugged branches, right?  It might be easier to merge those back with master.

**Comment by kmonson** [comment]
One of the two commits I mentioned is the one I branched the paper stuff
off of.

**Comment by lizutah** [comment]
Code is reintegrated, Juan is testing.
