### ISSUE TITLE
UnityMol Integration

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#401]
@sobolevnrm  recently started playing with Google Cardboard and was interested in it as an inexpensive way to bring VR/AR to our users for molecular electrostatics visualization.  Cardboard supports Unity-based VR apps so he started looking around for molecular visualization packages that supported Unity.  He discovered that UnityMol [3] was developed by an acquaintance (Marc Baaden, Paris) and had already been used for VR applications with Oculus Rift [4].  @lizutah, @sobolevnrm, & @keith923  had a call with Marc a few days ago and he is very interested in collaborating on UnityMol for our software and more generally for VR applications.

[3] UnityMol demos:  https://www.youtube.com/watch?v=CNR7wzcsqBs and https://www.youtube.com/watch?v=C8c047brpyw
[4] UnityMol and Oculus Rift:  https://www.youtube.com/watch?v=34VowF7uR-0&feature=youtu.be

**Comment by tlskillman** [comment]
The integration of UMol with VR tools is of interest to me also. I am associated with the Benaroya Autoimmune Research Institute. Through some lucky friend-of-a-friend connections I have gotten my hands on a pre-release Vive VR system. I successfully loaded and run the UnityMol_SVN project in Unity, but I have not yet succeeded at substituting the SteamVR CameraRig in for the UMol Camera in the project hierarchy.  Any thoughts or suggestions would be appreciated. Do you know where I could find out more about the Oculus implementation noted above?  Many thanks in advance.  -Tom

**Comment by lizutah** [comment]
Tom - we have also made some progress on UnityMol in Vine, in collaboration with Marc Baaden. Here is a sneak peak at what we are doing: https://www.youtube.com/watch?v=Xxb3W8jnnp8.

**Comment by tlskillman** [comment]
Ah Liz, That's so cool. Just what I had in mind. And it always 100 times cooler in VR than it is in videos. Might you be willing to share your work?  Either a Unity project file, or maybe some hints on how to integrate the CameraRig into Marc's published source code?

**Comment by nick-cramer** [comment]
Hi Tom, I am the one doing the actual development to integrate UnityMol with Vive/SteamVR and made that video. I am certainly open to sharing the Unity project I'm working on.  I'm not sure I can make the decision on this though. Let me chat with the team here at PNNL and Marc to figure out a path forward. 

My work is definitely a rough prototype and not part of Marc's codebase yet. Generally, we need to figure out how any VR work gets incorporated into the UnityMol distribution. I don't want to end up with too much fragmentation. But prototyping in a sandbox is fun too.

I completely agree ... the VR experience is 100x cooler than the video conveys. I have a lot more interaction planned for loading new data and modifying the vis properties while still in VR.

**Comment by bam93** [comment]
Hi, sorry for a late reply. Nick, I am happy for you to share the code with Tom. Just as a note on the UnityMol code release logic: UnityMol is Open Source, but we typically release the new(est) source code with added features only when a companion paper describing those features is coming out. In the periods between such official releases, I share the source code 'privately' with selected collaborators only and ask them to not redistribute it without checking back with me.

**Comment by tlskillman** [comment]
Hi Nick and Marc,

Thanks for the willingness to consider sharing your UnityMol pre-release with me. I certainly agree not to redistribute your code without your prior permission.  My intent would be to show some of the Principal Investigators here at BRI what is possible in terms of VR visualizing and interacting with molecular structures.  Since we study autoimmune disease here, it will be interesting to explore the [MHC/HLA](https://en.wikipedia.org/wiki/Major_histocompatibility_complex) binding complex. 

What would be the next step to getting access to your code?

Thanks,
Tom  
tskillman dot benaroyaresearch dot org

**Comment by nickcramer** [comment]
I'll reach out via email to get you the code. It looks like you are locate in Seattle. I am in Richland but I visit Seattle often. It would be neat to meet up sometime and learn more about how you might use this technology.
