### ISSUE TITLE
Test new geoflow API against old geoflow version

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#402]

**Comment by keith923** [comment]
We should update the Travis tests to build and test geoflow.

**Comment by lizutah** [comment]
I tested the new geoflow API against the old version (in 1.4.1) and have computed the same answer.  FYI, I fixed the bug in the old version to verify (from this commit:  https://github.com/Electrostatics/geoflow_c/commit/1c705e04cae8d3b595462449009a955ce8ff76c5).  The new output value is updated here (https://github.com/Electrostatics/apbs-pdb2pqr/commit/9bfde46760eb9b142608b7a5c1e95014d8c406bd) as well.

**Comment by keith923** [comment]
Awesome!  I'm going to reopen and assign to myself so that I don't forget to add geoflow to the Travis CI builds.

**Comment by lizutah** [comment]
good idea.  However, the example is broken until #404 is fixed.

**Comment by lizutah** [comment]
the geoflow-merge branch is merged with master.  @keith923  should be able to add it to travis

**Comment by keith923** [comment]
I've added this to the Travis CI scripts, and it's passing on my box.  The next Travis run will confirm that it's all good.

@kozlac would you like to add a README.md file for this one as well?  :)

**Comment by kozlac** [comment]
Will do.

**Comment by keith923** [comment]
Thanks!  Don't close the issue just yet though.  The Travis CI boxes don't have Eigen, upon which we depend, so I'll be addressing that problem under the auspices of this issue.

**Comment by keith923** [comment]
The tests should be working now.

**Comment by keith923** [comment]
Travis needs to go away.  Their Linux boxen have a version of GCC that doesn't support C++11.

**Comment by kozlac** [comment]
Created table with results in readme file. Closing now.
