### ISSUE TITLE
Add anchors to FAQs

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#403]
Needs anchors to each FAQ for reference later:
http://www.poissonboltzmann.org/docs/apbs-faq/

**Comment by kozlac** [comment]
Pushed the changes done in docs/apbs-faq.md file in [electrostatics.github.io](https://github.com/Electrostatics/electrostatics.github.io). @lizutah let me know if there is any problems targeting the anchors.

**Comment by lizutah** [comment]
fixed.  READMEs are updated.
