### ISSUE TITLE
Geoflow input file broken

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#404]
The exampe in /apbs/examples/geoflow no longer works after merging with master.  I think this has something to do with the removal of warnings in the build (#378) in file apolparm.c (from this commit: https://github.com/Electrostatics/apbs-pdb2pqr/commit/061d43c80c500917fc0f236ff81aef3899c07d9f).  When I comment out the return value, geoflow is happy.  The parameter parsing probably needs to be rewritten since this does not effect other apbs input files (that I can tell).

**Comment by kozlac** [comment]
@lizutah I made the changes in master and my local geoflow-branch. I tested the geoflow example and ran successfully. I will add the other keywords. Can I go ahead and close this issue or wait until I add the other keywords?

**Comment by lizutah** [comment]
go ahead and close, tagged with a commit.  For now, keep your changes to the geoflow-merge branch.

**Comment by kozlac** [comment]
Made changes to apolparm.c. Change the final return statement in function APOLparm_parseToken() to VRC_FAILURE. This will make it go into parsers in geoflow. See commit 2e2c59b.

**Comment by lizutah** [comment]
@kozlac, can we make the attached input file work?
[geoflow.in.txt](https://github.com/Electrostatics/apbs-pdb2pqr/files/68750/geoflow.in.txt)

I get the following error:
Parsing input file geoflow.in...
Vio_ctor2: Gethostbyname fail INET sock <> dueto <VIO_UNKNOWN_ERROR(0)>
read
PBEparm_check: PDIE not set!
NOsh:  GEOFLOW parameters not set correctly!
Error while parsing input file.

**Comment by lizutah** [comment]
@sobolevnrm - did you want geoflow to have it's own keyword (instead of being under elec)?

**Comment by keith923** [comment]
I know that he did want that originally.

**Comment by lizutah** [comment]
do we need these calculation types (MANUAL and NONE), too?
enum eGEOFLOWparm_CalcType {
    GFCT_MANUAL=0,  /**< GEOFLOW-manual */
    GFCT_AUTO=1,  /**< GEOFLOW-auto */
    GFCT_NONE=2 /**< not defined */
};
Do we need AUTO and NONE?

**Comment by kozlac** [comment]
For multigrid none or dummy (I can't remember top of my head) is used just to generate the pde parameters for other calculations. I don't think we would need it for geoflow.

**Comment by lizutah** [comment]
OK, let's get rid of MANUAL and NONE and throw an error if anything else is in the input file.

Also check bcfl and throw and error if any other boundary condition is set besides mdh (only one implemented for now, see #266).

**Comment by lizutah** [comment]
@kozlac fixed this in 1a71ee89f85bbdf454df0848b24ba19514d535b0.
