### ISSUE TITLE
Update README files in examples with 1.4.2 output values

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#407]
When we do the 1.4.2 "code freeze" we'll need to document it's output as stated in the title.

**Comment by keith923** [comment]
@kozlac could please you run the test suite and take the results and update the README files in the examples?

**Comment by keith923** [comment]
Use SHA 7d58385fb37dc8867ee5a8754b2ea8e2911de936 for running the tests.  No code changes after than SHA will be included in the release unless we find defects, and only commits to documentation after that will be allowed.

**Comment by kozlac** [comment]
Updated the tables with the new APBS1.4.2-binary. Closing now.

**Comment by keith923** [comment]
We should call the release 1.4.2, not 1.4.2-binary.  1.4.1-binary was actually the name of the last release, but this one is just 1.4.2.  Confusing?  Yes.  My humblest apologies.

**Comment by kozlac** [comment]
Changed to 1.4.2 . Closing (for good?) now.
