### ISSUE TITLE
Why does PDB2PQR/PDB2PKA fail on 2M6J?

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#408]
Is it because it's an NMR structure?  All of the pKas predicted in the PKA.DAT file are "-inf".

**Comment by sobolevnrm** [comment]
3D8G also has problems and it is *not* an NMR structure.

**Comment by kozlac** [comment]
@sobolevnrm, the reason it is printing inf's (for 2M6J) is coming from [pMC_mult.cpp:202 ](https://github.com/Electrostatics/apbs-pdb2pqr/blob/master/pdb2pqr/pdb2pka/pMC_mult.cpp). For each pH value one of the charges is being calculated to zero and hence the ratio comes as inf. I am working on tracking back why this is from the molecule.

**Comment by sobolevnrm** [comment]
We want to identify residues where all of the states have energies with absolute values greater than 80 (assuming units are kT).

**Comment by sobolevnrm** [comment]
Residues that have this problem are errors and the run should stop and these errors should be communicated to the user.

**Comment by lizutah** [comment]
Clarification: for this issue, just communicate to the user in stderr.  Making this error visible in the web server is issue #430.

**Comment by kozlac** [comment]
As per @sobolevnrm  and @keith923 conversation I modfied the pdb2pka calc_pKa method to check for unusually large interaction energies (abs(energy)>80kT) before passing the values to the Monte Carlo file. To see what would happen, if the energies were bigger than 80 kT I capped them at 80kT and pass them to the Monte Carlo method. The results were still showing infinities. However, if I capped the value to 10 kT the Monte Carlo Method returned the attached results with comparable results to those calculated with graph cut, and the calculated pKa's and very close to the model ones

**Comment by sobolevnrm** [comment]
Can you define "capping"?  I don't think we want to cap anything -- we want
to alert the user if those large numbers are encountered and raise an error.

**Comment by kozlac** [comment]
Yeah capping was probably  not the right word. I meant replace with 10 kT to see if the Monte Carlo method would still return inf's which did not. Do we want just throw and error and let the program continue or throw the error and terminate it?

**Comment by kozlac** [comment]
Added a check to verify that interaction energies are no larger than 80kt. If so the program throws an error message and terminates. I am closing this issue unless @sobolevnrm thinks otherwise?

**Comment by sobolevnrm** [comment]
You test the absolute value of the energy, right?  If so, then it should be
OK to close.  Thanks!

**Comment by keith923** [comment]
Just curious here.  If there are columns/rows in the interaction energies table that do not contain large values, could not those still be part of the solution?  In other words, if we were to remove the combinations that contained large values, could we not continue the calculation?

**Comment by kozlac** [comment]
The decision was made that if the absolute value of the interaction energy is  larger than 80kT then the program will stop and throw a message. (See PDB2PQ 2.1.1 release notes.)
