### ISSUE TITLE
Running 1JHG with PDB2PQR 2.0.0 on the NBCR server gives an error

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#409]
Traceback (most recent call last):
  File "/opt/pdb2pqr_2.0.0/pdb2pqr.py", line 62, in <module>
    mainCommand(sys.argv)
  File "main.py", line 740, in mainCommand
  File "main.py", line 341, in runPDB2PQR
  File "src/routines.py", line 1514, in runPDB2PKA
  File "pdb2pka/pka_routines.py", line 218, in runpKa
  File "pdb2pka/pka_routines.py", line 2261, in findTitratableGroups
  File "pdb2pka/pka_routines.py", line 2071, in getAtomsForPotential
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'

**Comment by kozlac** [comment]
@sobolevnrm I ran 1JHG in the server and with the following options:

--with-ph=7.0 --ph-calc-method=propka --apbs-input --ff=parse --verbose --summary 1JHG 1JHG.pqr

and it completed. I am also attaching the pqr and propka outputs. Did you run it with different parameters?

[ISSUE409.zip](https://github.com/Electrostatics/apbs-pdb2pqr/files/97767/ISSUE409.zip)

**Comment by kmonson** [comment]
The original run is using pdb2pka:

--with-ph=7.0 --ph-calc-method=pdb2pka --apbs-input --ff=parse --verbose
--summary 1JHG 1JHG.pqr

**Comment by kozlac** [comment]
@sobolevnrm as the trace back says, the error happens in [pka_routines.py:2071](https://github.com/Electrostatics/apbs-pdb2pqr/blob/master/pdb2pqr/pdb2pka/pka_routines.py). The method is trying to add charge=None to a running sum of type float. The offending atom is: 

HETATM 1826  CH2 TRP A 111      -3.079   9.320 -11.516  1.00 14.42           C

A quick and dirty fix would be to check if charge==None and if so do nothing but I don't know enough about pdb2pka and how the non-protein residues would affect the result.

**Comment by sobolevnrm** [comment]
It looks like this PDB entry includes an amino acid as a ligand and that
charges couldn't be assigned to it.  It would be great to have more
information on the error message for the user but I don't think this is a
problem we can fix directly.

**Comment by kozlac** [comment]
This problem is solved in PDB2PQR 2.1. I am running 1JGH following command:

`pdb2pqr --with-ph=7.0 --ph-calc-method=pdb2pka --apbs-input --ff=parse --verbose --summary 1JHG.pdb  1JHG.pqr`

I think is solved by ignoring the HETATM entries in the pdb file  altogether, @kmonson can you confirm this?

I am closing this issue unless there is any objections.

**Comment by kmonson** [comment]
Yes that is correct, but I wouldn't call it fixed. This method strips out
the entire ligand and never tells the user what it is doing.  If anything
it should either warn the user that it is removing HETATMs that are not
water or it should fail with a better error message.
