### ISSUE TITLE
BEM not building

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#413]
Changes to the out of source makefile has broken BEM.

**Comment by kozlac** [comment]
Seems to not being able to find the library created from code in /contrib/tabipb.

**Comment by kozlac** [comment]
BEM is building now.

**Comment by keith923** [comment]
Nice!  Can you include a link to the commit that fixed this?  In general you can reference the issue in your commit message and it'll happen automagically.

**Comment by kozlac** [comment]
I did. Is above the closing comment: https://github.com/Electrostatics/apbs-pdb2pqr/commit/fa535c4d53412f87e95b204d4f5751971bce5744

**Comment by keith923** [comment]
I'm blind!!!!  That's what my wife says anyway.  :smile:.  Sorry Juan, and thank you for being awesome.
