### ISSUE TITLE
OS X bundle library issue

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#419]
A user reports that DYLD_LIBRARY_PATH is not being properly set when he opens  the APBS bundle on OSX.  He uses tcsh, which I assume to be related to the problem.

**Comment by lwwilson1** [comment]
Is this the same issue as #450 ?  In which case I'd assume it's not related to tsch, since I get the same issue with bash

**Comment by keith923** [comment]
#450 I new to El Cap. So while it may be the same problem, I doubt it. The simplest explanation for this issue is the difference in the way bash and tcsh deal with env vars.

**Comment by lizutah** [comment]
only an issue for me... so closing. :-P
