### ISSUE TITLE
Generate 2-3 additional test cases for APBS BEM

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#42]
@lizutah

**Comment by keith923** [comment]
This _may_ be useful (excerpt of an email from Weihua):

> (2) You could start from the code I left to Nathan last summer, which has been already interfaced with APBS. Or if you plan to start from a standalone boundary element TABI solver, you can get the code from http://sourceforge.net/p/tabipb/code/ci/master/tree/ 
In each case, there are a directory called test proteins. You can always change the usrdata.in file to work on the protein called “oneb”, which is simple and essentially a spherical cavity.

**Comment by lwwilson1** [comment]
Added examples to display use of different surface meshers (MSMS, NanoShaper SES, and NanoShaper Skin) and different orders of treecode Taylor series expansion.
