### ISSUE TITLE
clean up gitrepo

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#422]
Recent investigation by @keith923 has revealed some large files that have been checked in and removed from this repository...  Let's see if we can clean some of these out and make clones faster.

**Comment by keith923** [comment]
As an aside, I updated my clone of the Sphinx repo last night, and it appears that someone recently grew it by ~500MB.  I think it may now contain the apbs-pdb2pqr repo.  :(

**Comment by sobolevnrm** [comment]
Oops!  It was supposed to be added as a sub module. Sorry.

**Comment by lizutah** [comment]
@keith923 - can we close this?

**Comment by keith923** [comment]
@lizutah no, not really.  I fixed the problem with the Sphinx repo, but this one is still as described above.

**Comment by keith923** [comment]
Something funky is happening when I try to push the cleaned up repo.  I manage to get it down to 83MB, but when I push it I get errors related to the pull requests:

```
To https://github.com/Electrostatics/apbs-pdb2pqr.git
 ! [remote rejected] refs/pull/1/head -> refs/pull/1/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/181/head -> refs/pull/181/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/184/head -> refs/pull/184/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/246/head -> refs/pull/246/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/247/head -> refs/pull/247/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/440/head -> refs/pull/440/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/440/merge -> refs/pull/440/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/444/head -> refs/pull/444/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/444/merge -> refs/pull/444/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/446/head -> refs/pull/446/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/448/head -> refs/pull/448/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/449/head -> refs/pull/449/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/452/head -> refs/pull/452/head (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/Electrostatics/apbs-pdb2pqr.git'
```

I've tried a few things to deal with this to no avail.  That said, I've got the clone down to less than half of what it was: ~198MB.  I'd love to trim it more, but I think I've spent more than enough time on this.
