### ISSUE TITLE
iAPBS CMake issue

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#428]
The iAPBS portion of the main CMakeLists.txt file attempts to invoke ADD_LIBRARY on routines.c, which was fine before we added support for building the Python shared library.  But it's redundant now, and a bug.

**Comment by rubadub** [comment]
I pushed a fix for this, iAPBS should now compile cleanly.

**Comment by keith923** [comment]
I recall that this is related to #429.  IIRC enabling this is what causes #429 to occur.

**Comment by lwwilson1** [comment]
Already fixed.
