### ISSUE TITLE
iAPBS Fortran wrappers

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#429]
iAPBS has an option to use Fortran wrappers.  However, the APBS API that it relies upon was changed several years ago when Fortran was removed from APBS.

The main question now is whether we want to see if we can fix the API, or simply disallow the Fortran wrappers, and perhaps remove the defunct functions.

**Comment by rubadub** [comment]
Hi Keith,

iAPBS does not depend on any APBS Fortran API. iAPBS is built as a library but there is included wrapper.f which is an example on how to use this iAPBS library from Fortran programs. This wrapper.f can be optionally built and I guess this triggers Fortran invocation you are seeing? You can enable/disable the wrapper building on the cmake command line.

Robert

**Comment by lwwilson1** [comment]
Echoing Robert's comments above. There was a small CMakeLists issue (fixed) that made it look like an error was occurring involving invoking Fortran where it was not. I changed the name of the BUILD_WRAPPER option to BUILD_iAPBS_FORTRAN_WRAPPER to reduce confusion over the make options
