### ISSUE TITLE
Why use atomname HSG in terminal CYS? And why atomname HN in CYM?

### ISSUE THREAD

**Issue by j3mdamas** [Electrostatics/apbs-pdb2pqr#451]
Checking the `dat/leap` of AmberTools15 (and I would guess the recent AmberTools would be the same), there is no `HSG` atom anywhere, in particular for NCYS or CCYS. The atomname is still `HG`. Using `runPDB2PQR` gives me that atomname that then fails in `tleap`:

```
FATAL:  Atom .R<CYS 31>.A<HSG 12> does not have a type.
```

Am I correct or am I missing something here?

This query shows me specific changes being performed on the `HG` atom: https://github.com/Electrostatics/apbs-pdb2pqr/search?q=HSG

**Comment by j3mdamas** [comment]
I updated the topic of the thread. The same question applies to changing the H in CYM to HN, even though this time I can find old Amber forcefields were that happened.

**Comment by sobolevnrm** [comment]
If this naming scheme is a problem, please explain why and suggest an alternative.  Note that AMBER is not the only force field used in APBS/PDB2PQR.

**Comment by j3mdamas** [comment]
Sorry, almost 4 years have passed since I opened this issue, I do not recall all the details. If AMBER did not change since then, the issue should still be valid. At that time, I fixed it on a fork from this repo and AMBER only specific files, which should not affect the behavior with other FFs. You can see it here: https://github.com/tonigi/apbs-pdb2pqr/pull/1/files.

**Comment by sobolevnrm** [comment]
@intendo or @mvaliev -- it should be pretty easy to patch master with https://github.com/tonigi/apbs-pdb2pqr/pull/1/files.  Can you please do that?

**Comment by j3mdamas** [comment]
If you're interested, I can open a PR.

**Comment by sobolevnrm** [comment]
Yes, please!

**Comment by j3mdamas** [comment]
Done

**Comment by sobolevnrm** [comment]
Fixed by https://github.com/Electrostatics/apbs-pdb2pqr/commit/766bba7fe45a5c4d61d644bdc966516b677ad4b0
