### ISSUE TITLE
Electrostatic Potential at position in pdb file

### ISSUE THREAD

**Issue by AFokas** [Electrostatics/apbs-pdb2pqr#455]
Hello,

I was wandering whether there exists a technique that would allow me to measure the electric potential at particularly point in the pdb; namely, how do the entries in the .dx file map to xyz coordinates in the pdb file.

Thanks,

Alexander

**Comment by kozlac** [comment]
Hello @AFokas, this [link](http://www.poissonboltzmann.org/docs/file-format-info/) explains how the outputted dx files by APBS are laid out. For a particular point that doesn't happen to be a grid point you could try using the [multivalue tool](http://www.poissonboltzmann.org/docs/apbs-utilities/) to get values at user supplied list of points. It uses spline interpolation. Please let me know if you have further questions. Thank you for using APBS!

**Comment by AFokas** [comment]
Hello,

Thank you for getting back to me. Although I seem to have apbs installed
and working, when I type "multivalue" into the command line it does not
seem to work. I cannot find any instructions on how to build the
multivalue.c program either. Could you point me in the right direction to
get this up and running?

Thanks,

Alexander

**Comment by keith923** [comment]
Which OS are you on, and what version of APBS are you using?

 - Keith


On Aug 22, 2016, at 07:13, AFokas <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

Thank you for getting back to me. Although I seem to have apbs installed
and working, when I type "multivalue" into the command line it does not
seem to work. I cannot find any instructions on how to build the
multivalue.c program either. Could you point me in the right direction to
get this up and running?

Thanks,

Alexander

**Comment by AFokas** [comment]
Linux x86_64 x86_64 x86_64 GNU/Linux
APBS-1.4.2.1-linux64

Thanks,
Alexander

**Comment by kozlac** [comment]
@AFokas if you did a "standard" installation most likely the multivalue tool is already build but for some reason is not in the your path. Please look in:

    $ls -l /path/to/installation/folder/for/apbs/tools/bin

There you should see the multivalue tool and others. To added to your path:

    $export PATH=/path/to/installation/folder/for/apbs/tools/bin:${PATH}

Please let us it this solve your issue. Thanks!!

**Comment by AFokas** [comment]
Hello,

That doesn't seem to be the issue. Perhaps I haven't installed correctly,
as in the APBS-1.4.2.1-linux64/bin there is only the apbs and mpe files.
Are there instructions to install from source? I have followed
http://www.poissonboltzmann.org/docs/apbs-installation/ but that does not
seem to build the tools.

Thanks,

Alexander

**Comment by kozlac** [comment]
@AFokas can you tell me what if you have the following folders:
    $ls -l .../APBS-1.4.2.1-linux64/share/apbs/tools/bin

**Comment by AFokas** [comment]
ls -l

-rw-r--r-- 1 asf40 tcm 253223 Jan  9  2016 analysis
-rw-r--r-- 1 asf40 tcm 140753 Jan  9  2016 benchmark
-rw-r--r-- 1 asf40 tcm 250475 Jan  9  2016 born
-rw-r--r-- 1 asf40 tcm 263124 Jan  9  2016 coulomb
-rw-r--r-- 1 asf40 tcm  23477 Jan  9  2016 del2dx
-rw-r--r-- 1 asf40 tcm 240705 Jan  9  2016 dx2mol
-rw-r--r-- 1 asf40 tcm 240661 Jan  9  2016 dx2uhbd
-rw-r--r-- 1 asf40 tcm 251046 Jan  9  2016 dxmath
-rw-r--r-- 1 asf40 tcm 268723 Jan  9  2016 mergedx
-rw-r--r-- 1 asf40 tcm 275341 Jan  9  2016 mergedx2
-rw-r--r-- 1 asf40 tcm 123669 Jan  9  2016 mgmesh
-rw-r--r-- 1 asf40 tcm 245198 Jan  9  2016 multivalue
-rw-r--r-- 1 asf40 tcm 272559 Jan  9  2016 similarity
-rw-r--r-- 1 asf40 tcm 250190 Jan  9  2016 smooth
-rw-r--r-- 1 asf40 tcm  21933 Jan  9  2016 tensor2dx
-rw-r--r-- 1 asf40 tcm 127693 Jan  9  2016 uhbd_asc2bin
-rw-r--r-- 1 asf40 tcm 239219 Jan  9  2016 value

This directory is in my path, however when I run the multivalue command
this happens;

pc6:~$ multivalue
-bash:
/scratch/asf40/bin/APBS-1.4.2.1-linux64/share/apbs/tools/bin/multivalue:
Permission denied


I am not the root user, perhaps this is the problem? However, the bin is
installed in my own directory.


Thanks,

Alexander

**Comment by kozlac** [comment]
@AFokas it seems you need to change the read/write permissions in that folder. To do that input the following:

    $cd </path/to/>/APBS-1.4.2.1-linux64/share/apbs/tools
    $chmod -R 755 bin/
    $cd bin

Now most likely the libraries needed by multivalue won't be in your library path. To include them:

    $export LD_LIBRARY_PATH=</path/to/>/APBS-1.4.2.1-linux64/lib:${LD_LIBRARY_PATH}
    $./multivalue

If everything went out correctly you should see the multivalue usage message.

**Comment by AFokas** [comment]
Fantastic, thank you for taking time to walk me through that.

Best,

Alexander

**Comment by kozlac** [comment]
@AFokas Awesome! Let us know if there are further questions. In the mean time I am closing this issue.
