### ISSUE TITLE
Potentials for proteins with embedded pigments

### ISSUE THREAD

**Issue by AFokas** [Electrostatics/apbs-pdb2pqr#456]
Hello,

I am attempting to calculate the potential at specific atoms in a protein with embedded pigments (http://www.rcsb.org/pdb/explore.do?structureId=3EOJ).  I am doing this using "multivalue" with xyz coordinates from the pdb file, however the pqr is not able to assign charges to the embedded pigments. Is there a way around this?

Thanks,

Alexander

**Comment by kozlac** [comment]
@Afokas You need to run the linked pdb through [PDB2PQR](http://nbcr-222.ucsd.edu/pdb2pqr_2.1.1/) in order to get a pqr file. PDB2PQR will assign charges to the molecule according to the chosen fields and parameters. You can read more on usage [here](http://www.poissonboltzmann.org/).  After you have the .pqr and .in file you can run it with APBS to obtained the potentials in a dx formatted file. Note that you can do all this from the PDB2PQR server above. After this step, you can use the multivalue tool. I hope this helps!

**Comment by AFokas** [comment]
Hello,

I have tried to use PDB2PQR but it does not seem to recognise the ligands in the pdb file. From the server, I am guessing that I need to provide a MOL2 file of the bacteriochlorophyll molecules, however I am not familiar with this; if I do not have it am I unable to use PDB2PQR?

**Comment by keith923** [comment]
@AFokas could you provide us with more information?  The error that you are getting when you run PDB2PQR, for example.

**Comment by AFokas** [comment]
From the command line;

python pdb2pqr.py --noopt --apbs-input --ff=amber --chain --verbose
--summary ../pdbs/0.pdb 0_3.pqr

And in the 0_3.pqr I find;
#######################################

REMARK   1 PQR file generated by PDB2PQR (Version master)
REMARK   1
REMARK   1 Command line used to generate this file:
REMARK   1 --noopt --apbs-input --ff=amber --chain --verbose --summary
../pdbs/0.pdb 0_3.pqr
REMARK   1
REMARK   1 Forcefield Used: AMBER
REMARK   1
REMARK   5
REMARK   5 WARNING: PDB2PQR was unable to assign charges
REMARK   5          to the following atoms (omitted below):
...

#######################################
which includes all the BCL (pigment) atoms

Thanks,

Alexander

**Comment by AFokas** [comment]
Is there any more information I can provide that will help resolve this?

**Comment by kozlac** [comment]
@AFokas we are looking into this. I'll get back to you as soon as I have more information. Thanks for your patience.

**Comment by sobolevnrm** [comment]
@AFokas -- this is the expected behavior.  If PDB2PQR does not include parameters for the molecules, then it will not assign charges.  Please see https://apbs-pdb2pqr.readthedocs.io/en/latest/pdb2pqr/extending.html for more information.
