### ISSUE TITLE
actin-dimer-parallel intermediate results failing

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#459]
The actin-dimer-parallel test is [failing](https://travis-ci.org/Electrostatics/apbs-pdb2pqr/jobs/154576673).  Investigate and fix so that it's not failing.

**Comment by lwwilson1** [comment]
I noticed this yesterday. The total energy is off by 0.1%, the other values are off by 0.007% to 0.001%. Is there any way to know if the test values are wrong?

**Comment by keith923** [comment]
@kozlac added those tests recently, so I'm hoping that he can determine if the tests are failing because something changed, or if it's because of a mistake when he created the tests.

**Comment by keith923** [comment]
Updated expected results to match, well the expected numbers.  See commit for more info.
