### ISSUE TITLE
Get the Release Ready

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#462]
- [x] Get everything built on Windows, OS X, and Linux
- [x] Create installation packages as done for the last release
- [x] Run the tests
- [x] Create a branch and put the following in it:
- [x] Updated release notes
- [x] Updated change log
- [x] Update example .md files with test results

**Comment by kozlac** [comment]
I am using the following cmake flags to build in Linux:

-DCMAKE_BUILD_TYPE=Release -DBUILD_DOC=ON -DENABLE_FETK=ON \
-DENABLE_GEOFLOW=ON -DENABLE_BEM=ON -DENABLE_PB_S_AM=ON

For Windows:

-DENABLE_GEOFLOW=ON -DENABLE_BEM=ON -DENABLE_PB_S_AM=ON

**Comment by kozlac** [comment]
Because of C standard mismatches between VS15 and GCC I am removing the PB-SAM from the Windows build until these are resolved.

**Comment by keith923** [comment]
## Test Results

Test | Windows 7 (kts) | OS X (kts) |
-----|------------------|------------|
born |  👍 | 👍 
actin-dimer-auto |   | 👍 
actin-dimer-parallel |  | 👍 
alkanes |  | 👍 
FKBP | 👍  | 👍 
hca-bind |  | 👍 
ionize |  | 👍 
ion-pmf |  | 👍 
ion-protein |  | 👍 
pka-lig |  | 👍 
point-pmf |  | 👍 
solv |  | 👍 
geoflow |  | 👍 
bem |  | 👍 
bem-pKa |  | 👍 
bem-binding-energy |  | 👍 
pbam |  | 👍 
pbsam |  | 👍 
protein-rna | 👍  | 👍

**Comment by keith923** [comment]
## Windows installer Issues
* I did find the documentation and examples -- there were in the share directory and didn't expect them to be there.  That said, I think it's fine that they stay where they are.
* We used to dump APBS off the root.  I think that if we don't continue to do that users may get confused.  What do you think?
* We should use the icon that Minju created on the APBS executable.
* We used to offer to put APBS on the desktop.  I think we did anyway.  Should we offer to do that?

**Comment by kozlac** [comment]
@keith923 yeah I was trying to mimic the folder structure of the linux one. I can change the msi to install on the desktop. I will go ahead and also add the /programmer folder.

**Comment by kozlac** [comment]
Closing this as we already let the release loose. The only thing to remember is that PBSAM is not building on Windows as of yet.
