### ISSUE TITLE
--hbond option gone in 2.1.1?

### ISSUE THREAD

**Issue by jaredsagendorf** [Electrostatics/apbs-pdb2pqr#465]
I can't find any documentation of this change through google or through the release notes: http://www.poissonboltzmann.org/news/comp_pdb2pqr_release_history/

but version 2.0.0 had an --hbond option, which would print out a list of hydrogen bonds in the structure. This option has vanished in the newer release. Any explanation as to why?

**Comment by keith923** [comment]
Do either of @kozlac or @kmonson have any insight into this?

**Comment by kmonson** [comment]
--hbond was/is implemented through an extension. I just checked and it's still there in master and the latest release. If there is an error loading the extension then the program would exit with an error.

Are you running one of the prepackaged  binary releases?

**Comment by kmonson** [comment]
I just checked the latest windows release (all releases use the same configuration file when built) and the hbond extension is in there. Does your copy of the software have an hbond.py file in the extensions directory?

**Comment by jaredsagendorf** [comment]
Ahh I see, yes I'm running the pre-packaged binary. So I'll have to compile from source and include the extension to use this option? And yes, hbond.py is included in the extensions directory. 

I guess my confusion stemmed from the fact that the previous version I was running (2.0.0) included the hbond extension in the binary.

Thanks for the responses.

**Comment by kmonson** [comment]
Hmm, the extensions are supposed to be included in the binary packages. You should not have to compile it. If there is an extension directory with an hbond.py file it should work. This might be a bug. 

Do you see any hbond related options if you run with --help? At some point I consolidated some of the extensions together. Maybe it goes by a different name? I thought I did that prior to 2.0.0 and I thought --hbond was unchanged.
