### ISSUE TITLE
APBS-1.5-linux64 binary release requires g++ version 5 libraries installed?

### ISSUE THREAD

**Issue by rubadub** [Electrostatics/apbs-pdb2pqr#468]
The 1.5 linux64 binary release requires GLIBCXX_3.4.21 during runtime. These g++ 5 libraries are available only on recent Ubuntu distros. The latest Centos/Redhat 7.2 is still using gcc 4.8. This means this binary release won't work on any stock Centos/Redhat and older Ubuntu distros. Users will have to upgrade their gcc to be able to use the pre-built apbs binary (which is not trivial).

**Comment by keith923** [comment]
Sadly none of us ran into this as an issue.  I mean, who doesn't want to always run with the latest and greatest, right?

Juan is going to rebuild the binaries to work with GCC 4.8.

**Comment by kozlac** [comment]
Release has been updated with binaries built with GCC 4.8
