### ISSUE TITLE
Why are ``srfm``, ``srad``, etc. included in ``bem-manual`` input files when the surface type is determined by the mesh?

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#483]

**Comment by lwwilson1** [comment]
``srad`` is used by TABI-PB as the probe radius parameter that's fed into MSMS or NanoShaper when either one is called to build a surface. ``sfrm`` and ``swin``, however, are not used; I can remove these.

**Comment by sobolevnrm** [comment]
Can you please update the code/documentation accordingly?

Thanks!

**Comment by lwwilson1** [comment]
Will do
