### ISSUE TITLE
No heavy atoms found for RNA coordinates

### ISSUE THREAD

**Issue by chenzhao-CZ** [Electrostatics/apbs-pdb2pqr#506]
I have encountered problems when I tried to generate pqr file for APBS using AMBER force filed on a RNA molecule. The error message is something like no heavy atoms found. However, the coordinates is just a regular RNA molecule that is consistent with AMBER naming scheme. What should I try to solve this problem?

**Comment by kozlac** [comment]
Hello @chenzhao-CZ, could you tell us what if you are using PDB2PQR (server or local install, if local what version?) and maybe share with us the pdb file you are using?

**Comment by chenzhao-CZ** [comment]
Sorry for the delayed reply as I was traveling the last weekend. I have PDB2PQR version 2.1.1 on a local machine. The PDB file has PDBID 4FAQ. Thank you very much!

**Comment by speleo3** [comment]
> For RNA the residue names need to be change to RA, RC, RG, and RU

See https://sourceforge.net/p/pdb2pqr/mailman/message/33298335/
