### ISSUE TITLE
g_mmpbsa calculation

### ISSUE THREAD

**Issue by dplizyy** [Electrostatics/apbs-pdb2pqr#510]
Hi, developers of APBS,

Here I report a bug of APBS in reading PQR file.

I have some PQR files in ambPQR format. When I run APBS calculation, I got the following error information:

Parsing input file p2AaZppA.in...
NOsh:  Deprecated use of ION keyword! Use key-value pairs
NOsh:  Deprecated use of ION keyword! Use key-value pairs
NOsh:  Deprecated use of ION keyword! Use key-value pairs
NOsh:  Deprecated use of ION keyword! Use key-value pairs
Parsed input file.
Got paths for 1 molecules
Reading PQR-format atom data from p2AaZppA.pqr.
Valist_readPQR:  Error parsing atom 1!
Please double check this atom in the pqr file, e.g., make sure there are no concatenated fields.
Error reading molecules!

After checking the PQR file, I found that the first and last residues'name were wrong in the PQR file:

ATOM      1  N    NALA   192     -51.730-160.850  81.990   0.141   1.550
ATOM      2  H1   NALA   192     -50.730-160.800  82.120   0.200   1.200
ATOM      3  H2   NALA   192     -52.140-160.040  82.420   0.200   1.200
ATOM      4  H3   NALA   192     -51.990-161.700  82.470   0.200   1.200
ATOM      5  CA   NALA   192     -52.130-160.830  80.570   0.096   1.700
ATOM      6  HA   NALA   192     -51.570-161.650  80.140   0.089   1.200
ATOM      7  CB   NALA   192     -51.670-159.560  79.850  -0.060   1.700
ATOM      8  HB1  NALA   192     -52.140-159.700  78.880   0.030   1.200
ATOM      9  HB2  NALA   192     -52.260-158.770  80.330   0.030   1.200
ATOM     10  HB3  NALA   192     -50.600-159.430  79.970   0.030   1.200
ATOM     11  C    NALA   192     -53.620-161.060  80.360   0.616   1.700
ATOM     12  O    NALA   192     -54.370-160.550  81.190  -0.572   1.520
ATOM     13  N     PRO   193     -54.010-161.690  79.250  -0.255   1.550
ATOM     14  CD    PRO   193     -53.210-162.380  78.260   0.019   1.700
.
.
.
ATOM   3581  HE2   MET   422     -68.070-154.080  47.280   0.068   1.200
ATOM   3582  HE3   MET   422     -66.950-152.980  46.560   0.068   1.200
ATOM   3583  C     MET   422     -71.000-158.100  45.100   0.597   1.700
ATOM   3584  O     MET   422     -70.500-158.810  44.220  -0.568   1.520
ATOM   3585  N    CASP   423     -72.210-157.550  44.990  -0.519   1.550
ATOM   3586  H    CASP   423     -72.480-156.960  45.760   0.306   1.200
ATOM   3587  CA   CASP   423     -72.990-157.520  43.760  -0.182   1.700
ATOM   3588  HA   CASP   423     -72.710-158.360  43.130   0.105   1.200
ATOM   3589  CB   CASP   423     -74.500-157.710  43.950  -0.068   1.700
ATOM   3590  HB1  CASP   423     -75.010-157.920  43.010  -0.021   1.200
ATOM   3591  HB2  CASP   423     -74.910-156.790  44.350  -0.021   1.200
ATOM   3592  CG   CASP   423     -74.850-158.840  44.900   0.885   1.700
ATOM   3593  OD1  CASP   423     -74.440-159.970  44.570  -0.816   1.520
ATOM   3594  OD2  CASP   423     -75.600-158.630  45.890  -0.816   1.520
ATOM   3595  C    CASP   423     -72.640-156.360  42.850   0.726   1.700
ATOM   3596  OC1  CASP   423     -72.580-156.480  41.600  -0.789   1.520
ATOM   3597  OC2  CASP   423     -72.380-155.260  43.370  -0.789   1.520
ATOM   3598  C7    LIG   424     -54.410-155.360  49.800  -0.267   1.700
ATOM   3599  C4    LIG   424     -54.560-156.630  50.140  -0.072   1.700
ATOM   3600  C3    LIG   424     -54.430-157.030  51.590  -0.296   1.700
ATOM   3601  C2    LIG   424     -53.550-158.280  51.780   0.345   1.700
ATOM   3602  C1    LIG   424     -53.900-159.420  50.820  -0.051   1.700

**Comment by sobolevnrm** [comment]
Hello --

I have Cc'ed some of the other developers for their help with this issue.
I think the primary problem is the fact the coordinate fields run
together.  If you use the "add whitespace" option with PDB2PQR, it should
resolve this issue.

Thank you,

Nathan

**Comment by dplizyy** [comment]
However I didn't use PDB2PQR, I used a one step calculationcommand to calculate g_mmpbsa between receptor and ligand: g_mmpbsa -f md.xtc -s md.tpr -n index.ndx -i pbsa.mdp -pdie 2 -pbsa -decomp -tu ns
If calculation was correct, I will obtain six files: energy_MM.xvg, contrib_MM.datpolar.xvg, contrib_pol.datapolar.xvg, contrib_apol.dat. But, now I got two additional files: pErjddLA.in and pErjddLA.pqr. So, I really don't know how to use the "add whitespace" option with PDB2PQR that you suggest method to resolve this issue. Could you teach me in detail? Thank you very much!

2018-04-09 

lidongping1228 



发件人：Nathan Baker <notifications@github.com>
发送时间：2018-04-09 11:08
主题：Re: [Electrostatics/apbs-pdb2pqr] g_mmpbsa calculation (#510)
收件人："Electrostatics/apbs-pdb2pqr"<apbs-pdb2pqr@noreply.github.com>
抄送："dplizyy"<lidongping1228@sina.com>,"Author"<author@noreply.github.com>

Hello --

I have Cc'ed some of the other developers for their help with this issue.
I think the primary problem is the fact the coordinate fields run
together. If you use the "add whitespace" option with PDB2PQR, it should
resolve this issue.

Thank you,

Nathan

**Comment by kozlac** [comment]
Hello @dplizyy , like @sobolevnrm  said, the problem arises from the concatenated fields. You mentioned that you did not use PDB2PQR to obtain this file. Which software did you use?

**Comment by dplizyy** [comment]
APBS

2018-04-16 

lidongping1228 



发件人：Juan <notifications@github.com>
发送时间：2018-04-11 23:05
主题：Re: [Electrostatics/apbs-pdb2pqr] g_mmpbsa calculation (#510)
收件人："Electrostatics/apbs-pdb2pqr"<apbs-pdb2pqr@noreply.github.com>
抄送："dplizyy"<lidongping1228@sina.com>,"Mention"<mention@noreply.github.com>

Hello @dplizyy , like @sobolevnrm said, the problem arises from the concatenated fields. You mentioned that you did not use PDB2PQR to obtain this file. Which software did you use?

**Comment by sobolevnrm** [comment]
The code is behaving as expected; the coordinates need to be separated by whitespace.
