### ISSUE TITLE
calculating non-protein electrostatics

### ISSUE THREAD

**Issue by dvdvbrn** [Electrostatics/apbs-pdb2pqr#511]
Hello everyone,

I don't think this issue with APBS, but rather with me and my input files. If there is more preferred resource for this type of questions please redirect me there, as of now I will ask it here...

I am trying to calculate electrostatic potential of nylon crystal with APBS, but the calculation is being killed with this kind of output:

=======================================
This executable compiled on Oct 17 2016 at 16:11:10

Parsing input file 20180410_apbs-input.in...
rank 0 size 1...
read
Parsed input file.
Got paths for 1 molecules
Reading PQR-format atom data from 20180409_nylon-crystal-PDB2PQR-processed.pqr.
  9999 atoms
  Centered at (5.393e+01, 7.398e+01, 8.006e+00)
  Net charge -1.25e+00 e
Preparing to run 2 PBE calculations.
----------------------------------------
CALCULATION #1: MULTIGRID
  Setting up problem...
  Vpbe_ctor:  Using max ion radius (0 A) for exclusion function
  Debye length:  0 A
  Current memory usage:  12755.955 MB total, 12755.955 MB high water
  Using cubic spline charge discretization.
  Grid dimensions: 321 x 545 x 289
  Grid spacings: 0.785 x 0.788 x 0.746
  Grid lengths: 251.185 x 428.679 x 214.751
  Grid center: (53.928, 73.984, 8.006)
  Multigrid levels: 4
  Molecule ID: 1
  Linearized traditional PBE
  Single Debye-Huckel sphere boundary conditions
  0 ion species (0.000 M ionic strength):
  Solute dielectric: 2.000
  Solvent dielectric: 78.540
  Using "molecular" surface definition;harmonic average smoothing
  Solvent probe radius: 1.400 A
  Temperature:  298.150 K
  Electrostatic energies will be calculated
  Total electrostatic energy = 1.134353099376E+05 kJ/mol
  Calculating forces...
----------------------------------------
CALCULATION #2: MULTIGRID
  Setting up problem...
  Vpbe_ctor:  Using max ion radius (0 A) for exclusion function
Killed
=====================================
Is this because my system is too big? Any help would be appreciated!!!

Thanks,

Vitali Stanevich
Process Development Scientist,
Janssen Pharmaceuticals

**Comment by dvdvbrn** [comment]
Sorry for the junk in the upper half of comment - afterlunch brain shutdown issues :(

**Comment by kozlac** [comment]
Hello @dvdvbrn , it may be memory related since at the end of calculation one the memory usage is about 13gigs. What are your system specs? If you can share your .in, the io.mc created after running APBS, and .pqr files I could make sure nothing else is going on. If so, please send them to juan.brandi-lozano@pnnl.gov. Thanks!!
