### ISSUE TITLE
Which takes precedence - "parm" or pdb2pqr?

### ISSUE THREAD

**Issue by jaredsagendorf** [Electrostatics/apbs-pdb2pqr#517]
Hello, suppose you read in charge/radii/well parameters using the READ parm ... END statement, but you are also reading in in .pqr files with assigned charges and radii.

Which takes precedence? Meaning which charge and radii parameters are actually being used?

Thanks.

**Comment by sobolevnrm** [comment]
Hello --

If you read in both a PQR and parameter file, you should get a warning from
APBS that the PQR charge/radius information will be over-written by the
information in the parameter file.

Thank you,

Nathan
