### ISSUE TITLE
Fix TINKER support (to use APBS 1.4.x)

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#52]
Support for integrating APBS with TINKER (http://dasher.wustl.edu/tinker/) has been broken during the migration from Automake to Cmake to Scons to Cmake to...  We should fix it.

**Comment by mchun0630** [comment]
I tested TINKER with APBS 1.3 and it works. I emailed Jay Ponder and it seems that updating to APBS 1.4 is lower on his list of priorities, so for now it's just the 1.3 version. I do have an apbs test suite if you want that.

**Comment by lizutah** [comment]
@sobolevnrm - do you want us to try to upgrade TINKER to 1.4.x?

**Comment by sobolevnrm** [comment]
Yes, please!

**Comment by lizutah** [comment]
I put the test suite on our share, here: smb://PNLFS12/Electrostatics/code/TINKER/apbs-test.tar
"TINKER-APBS Poisson-Boltzmann Solvation Energy Test Cases"
It contains the following files:
0README    
apbstest.f 
crn.xyz    
enh.xyz    
fsv.xyz    
pgb.xyz    
tinker.key
vii.xyz
