### ISSUE TITLE
missing modified phosphorylated residue in PQR file

### ISSUE THREAD

**Issue by etillym** [Electrostatics/apbs-pdb2pqr#521]
I am a new user
I am using the web interface to produce the PQR AND APBS files, for visualization in VMD.
I am visualizing an SH2 domain binding to a phosphorylated tyrosine within a peptide. File is 1LCJ
I was able to visualize the electrostatic potential of thee SH2 domain nicely in VMD
The peptide is missing the modified phosphorylated tyrosine (designated PTR) residue 204.

It seems that it is missing in the PQR file

PQR file:
REMARK   1 PQR file generated by PDB2PQR (Version 2.0.0)
REMARK   1
REMARK   1 Command line used to generate this file:
REMARK   1 --with-ph=7.0 --ph-calc-method=propka --drop-water --apbs-input --ff=parse --verbose --summary peptide1lcj.pdb peptide1lcj.pqr
REMARK   1
REMARK   1 Forcefield Used: PARSE
REMARK   1
REMARK   1 pKas calculated by propka and assigned using pH 7.00
REMARK   1
REMARK   5
REMARK   5 WARNING: PDB2PQR was unable to assign charges
REMARK   5          to the following atoms (omitted below):
REMARK   5              26 N in PTR 204
REMARK   5              27 CA in PTR 204
REMARK   5              28 C in PTR 204
REMARK   5              29 O in PTR 204
REMARK   5              30 CB in PTR 204
REMARK   5              31 CG in PTR 204
REMARK   5              32 CD1 in PTR 204
REMARK   5              33 CD2 in PTR 204
REMARK   5              34 CE1 in PTR 204
REMARK   5              35 CE2 in PTR 204
REMARK   5              36 CZ in PTR 204
REMARK   5              37 OH in PTR 204
REMARK   5              38 P in PTR 204
REMARK   5              39 O1P in PTR 204
REMARK   5              40 O2P in PTR 204
REMARK   5              41 O3P in PTR 204
REMARK   5 This is usually due to the fact that this residue is not
REMARK   5 an amino acid or nucleic acid; or, there are no parameters
REMARK   5 available for the specific protonation state of this
REMARK   5 residue in the selected forcefield.
REMARK   5
REMARK   6 Total charge on this protein: -3.0000 e
REMARK   6

What can I do to create a PQR file for the small peptide that contains the missing phosphorylated residue?

**Comment by sobolevnrm** [comment]
Hello,

This error typically means that the force field you’ve chosen does not have parameters for your residue. You need to supply those parameters yourself of chose a force field that supports your residue. I’ve added @Engel, Dave W<mailto:dave.engel@pnnl.gov> , @Brandi-Lozano, Juan M<mailto:juan.brandi-lozano@pnnl.gov> , @Offor, Elvis<mailto:elvis.offor@pnnl.gov> , and @Rallo, Robert<mailto:robert.rallo@pnnl.gov> for help with this problem.

Thank you.

—
Nathan Baker
Sent from my mobile device

**Comment by etillym** [comment]
@sobolevnrm 
thanks for your response.  Does one of the provided force field choices in the web resource to generate PQR file recognize phosphorylated residues (PTR = phosphotyrosine)?

**Comment by sobolevnrm** [comment]
Hello.  Unfortunately, we do not currently have parameters for phosphotyrosine.  They can be added by following the documentation at https://apbs-pdb2pqr.readthedocs.io/en/latest/pdb2pqr/extending.html.
