### ISSUE TITLE
PDB with 2 ZN+ ligands

### ISSUE THREAD

**Issue by skigirl618** [Electrostatics/apbs-pdb2pqr#524]
Hello,

         I have a PDB file that contains 2 added ZN+ ligands that I need to look at the electrostatic potential. In order to use APBS I tried to run the file through PDB2PQR but I got an error message. I do not know if I need to use different settings, etc. so I was looking for some advice. I have attached my PDB below.
[Refined C1 domain with both zincs copy.txt](https://github.com/Electrostatics/apbs-pdb2pqr/files/3275838/Refined.C1.domain.with.both.zincs.copy.txt)

**Comment by kozlac** [comment]
Hello @skigirl618! To include ligands in the calculations you need to provide their corresponding mol2 files/
Please look at [this example](https://apbs-pdb2pqr.readthedocs.io/en/latest/examples/parameterizing-ligands.html) and let me know if you get stuck. Thanks!

**Comment by skigirl618** [comment]
Hello Juan,

         I am working with homology models and I do not have mol2 files so how do I obtain those? In addition, it seems that there is only 1 upload slot of a mol2 file on the PDB2PQR server, but I have 2 ligands (so I assume I would have 2 files). How do I work around that? Thanks for the help!

Sincerely,
         Abbey

**Comment by kozlac** [comment]
Unfortunately, we only support one ligand at the moment. To get the mol2 file you can go to http://davapc1.bioch.dundee.ac.uk/cgi-bin/prodrg/ and copy paste the relevant pdb entries.
