### ISSUE TITLE
terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by amaurypm** [Electrostatics/apbs-pdb2pqr#528]
Hello,
I am trying to run apbs with a viral capsid (> 30,000 residues) and apbs crash.
For example, the last lines of the output:
...
  Debye length:  7.8566 A
  Current memory usage:  34859.972 MB total, 34859.972 MB high water
  Using cubic spline charge discretization.
  Grid dimensions: 609 x 609 x 609
  Grid spacings: 0.813 x 0.812 x 0.813
  Grid lengths: 494.034 x 493.943 x 494.057
  Grid center: (366.490, 141.841, 141.679)
  Multigrid levels: 4
  Molecule ID: 1
  Linearized traditional PBE
  Single Debye-Huckel sphere boundary conditions
  2 ion species (0.150 M ionic strength):
    1.380 A-radius, 1.000 e-charge, 0.150 M concentration
    1.810 A-radius, -1.000 e-charge, 0.150 M concentration
  Solute dielectric: 2.000
  Solvent dielectric: 78.540
  Using "molecular" surface definition;harmonic average smoothing
  Solvent probe radius: 1.400 A
  Temperature:  298.150 K
  Electrostatic energies will be calculated

terminated by signal SIGSEGV (Address boundary error).

I have plenty of RAM, 126 GB, and apbs is not near this value before crashing.

**Comment by kozlac** [comment]
Hello @amaurypm ! Could you share your `.in` and `pqr` file to help reproduce and debug the problem?

**Comment by amaurypm** [comment]
Here they go.

[model_AAV2.zip](https://github.com/Electrostatics/apbs-pdb2pqr/files/3580757/model_AAV2.zip)

**Comment by sobolevnrm** [comment]
The input file for this example was set up incorrectly:  most of the atoms were off the mesh.
