### ISSUE TITLE
GLIBCXX and CXXABI not found

### ISSUE THREAD

**Issue by mwscandura** [Electrostatics/apbs-pdb2pqr#531]
When attempting to invoke apbs get the following error:
 
`apbs: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by apbs)'
'apbs: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by apbs)'
'apbs: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by apbs)`

i'm unfamiliar with what these are, where they should be, why they'd be missing etc. I'm also pretty new to this kind of coding and APBS. any help appreciated

**Comment by sobolevnrm** [comment]
Hello -

I'm adding @Brandi-Lozano, Juan M <juan.brandi-lozano@pnnl.gov> and @Offor,
Elvis <elvis.offor@pnnl.gov> for their help with this issue.

Thanks,

Nathan

**Comment by kozlac** [comment]
Hello @mwscandura , what linux distribution, or more precisely, what version of gcc are you using? That error occurs when the system's standard c/c++ libraries are incompatible with the compiler used to create the APBS binary.

**Comment by sobolevnrm** [comment]
Hi @mwscandura.  I'm going to close this issue because we're unable to proceed without the information @kozlac requested.  If you're able to provide that information, then we'll reopen the issue.  Thanks.
