### ISSUE TITLE
MPI-compiled version adds "PE0" to output file names 

### ISSUE THREAD

**Issue by chelsell** [Electrostatics/apbs-pdb2pqr#533]
I'm using APBS 1.5 on Ubuntu 18.04. In a variety of circumstances, APBS is adding the string "PE0" the end of filenames for outputs like dielectric maps. Here's an excerpt from an output file:

```  Electrostatic energies will be calculated
  X-shifted dielectric map to be written to dielx_1.dx
  Y-shifted dielectric map to be written to diely_1.dx
  Z-shifted dielectric map to be written to dielz_1.dx
  Kappa map to be written to kappa_1.dx
  Charge distribution to be written to charge_1.dx
  Skipping solve for mg-dummy run; zeroing solution array
  Total electrostatic energy = 0.000000000000E+00 kJ/mol
  Calculating forces...
  Writing x-shifted dielectric map to dielx_1-PE0.dx
  Writing y-shifted dielectric map to diely_1-PE0.dx
  Writing z-shifted dielectric map to dielz_1-PE0.dx
  Writing kappa map to kappa_1-PE0.dx
  Writing charge distribution to charge_1-PE0.dx
```

I don't appear to have any control over whether this string is added to the filenames--the input file certainly makes no mention of "-PE0"

This seems to be a known bug in older versions compiled with MPI:
https://sourceforge.net/p/apbs/mailman/message/24456374/

I can confirm that recompiling APBS without MPI solves this problem, but it seems like a silly reason not to use MPI. Also it seems like compilation with MPI is the default if it can be detected--I could only get this bug to go away by specifying `DENABLE_MPI=OFF`

**Comment by sobolevnrm** [comment]
Hi Cole -

This is the expected behavior.  Is it causing problems with other software
you're using in conjunction with APBS?

Thanks,

Nathan

**Comment by chelsell** [comment]
Hi Nathan,

Yeah, I was having trouble with this while running software that depends on APBS. I can definitely patch that software to not be so literal about the names of APBS outputs, but I was worried that other things might be systematically different between APBS with MPI and APBS without. Is there documentation that explains this difference and any others?

**Comment by sobolevnrm** [comment]
Hello -

There are some differences in output formatting and naming of the files but
these should be the only differences you encounter.

Thank you,

Nathan

**Comment by sobolevnrm** [comment]
I'm going to close this issue for now.  If there are specific software packages affected by this behavior, please let us know and we'll address those separately.
