### ISSUE TITLE
Unable to use inputgen.py with python3

### ISSUE THREAD

**Issue by lvotapka** [Electrostatics/apbs-pdb2pqr#534]
Hi everyone,

I can't seem to be able to run inputgen with Python 3.7.4:

```
$ python inputgen.py 
  File "inputgen.py", line 68
    self.async = 0
             ^
SyntaxError: invalid syntax
```

However, if I run with Python 2.7.12, it works:

```
$ python2 inputgen.py 
Invalid argument list!

Use this script to generate new APBS input files or split an existing
parallel input file into multiple async files.

Usage: inputgen.py [opts] <filename>

```
And then the arguments are listed...

I am just getting used to using python3 myself, so I have no idea what might be causing this problem...

**Comment by speleo3** [comment]
There is an open pull request which fixes this: https://github.com/Electrostatics/apbs-pdb2pqr/pull/516

I don't know why it hasn't been merged yet.

**Comment by lvotapka** [comment]
Ah so it looks like "async" is a reserved keyword in Python 3.

**Comment by sobolevnrm** [comment]
@kozlac and @intendo are working on the Python3 upgrade.  We hope to release soon.

**Comment by intendo** [comment]
This has been resolved and upgraded to Python3.
