### ISSUE TITLE
Multivalue - libraries not found

### ISSUE THREAD

**Issue by ssunidhi** [Electrostatics/apbs-pdb2pqr#536]
I updated the library path so that it points to </path/APBS-1.4.2.1-linux64/lib>, but still the following error is popping up each time:

./multivalue: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

It is because the unzipped directory doesn't have libreadline.so.6 in the lib folder. Kindly advise what should be done to resolve this issue.

@kozlac you responded to one thread which was similar to this issue. Kindly help.

**Comment by kozlac** [comment]
Hello @ssunidhi, this is not an APBS error. It seems you are missing the readline library in your system. What OS are you using? In Ubuntu, for example, you would do:

`sudo apt install libreadline-dev`

**Comment by AlexandrParkhomenko** [comment]
core/readline 8.0.004-1 [installed]
    GNU readline library

recompile!

**Comment by sobolevnrm** [comment]
@ssunidhi - were you able to resolve this issue?

**Comment by ssunidhi** [comment]
Yes I was. Python 2 was needed instead of python 3.

**Comment by sobolevnrm** [comment]
Great!
