### ISSUE TITLE
baker.css no longer available for docs

### ISSUE THREAD

**Issue by RizzerOnGitHub** [Electrostatics/apbs-pdb2pqr#537]
Docs at pdb2pqr/doc/userguide.html, pdb2pqr/doc/programmerguide.html, pdb2pqr/doc/pydoc/index.html, if not elsewhere, all use baker.css as stylesheet, from http://agave.wustl.edu/css/baker.css

But this url no longer exists. Should the css be changed? updated? removed?

**Comment by sobolevnrm** [comment]
Thank you for submitting this issue.  Are you referring to the documentation deployed on the web or distributed with the source code?

**Comment by RizzerOnGitHub** [comment]
The source code, https://github.com/Electrostatics/apbs-pdb2pqr/blob/master/pdb2pqr/doc/userguide.html etc

**Comment by sobolevnrm** [comment]
Commit faadd5f956698b4e4d0bdfb3d5138de5fedd1a5e actually addressed this, too... but @sobolevnrm mentioned the wrong issue in the commit log.
