### ISSUE TITLE
Problem downloading pqr-file

### ISSUE THREAD

**Issue by sarsv** [Electrostatics/apbs-pdb2pqr#539]
Hi!
After running pdb2pqr generating the output files I can't download the pqr-file, I can only open it as a text file. Does anyone have an idea of how I can download it as a pqr-file?

Best,
Sara

**Comment by sobolevnrm** [comment]
Hi Sara --

Can you please send us the job id?

Thank you,

Nathan

**Comment by sarsv** [comment]
Hi,

Here is the link to the job (couldn't find any job-id):
http://nbcr-222.ucsd.edu/pdb2pqr_2.1.1/querystatus.cgi?jobid=15872536569&calctype=pdb2pqr&fbclid=IwAR3UUCXXLjSbzI9Tf5mgN_VU8K4BI2liplkY2NSJgAfNA5hXY_3sHte8ut0

Kind regards,
Sara
________________________________

**Comment by sobolevnrm** [comment]
It looks like things are working as intended:  you need to right-click the link and select "Save link as..." or equivalent.  Also, please be sure to check out the new version of our server at http://server.poissonboltzmann.org.

**Comment by sarsv** [comment]
Thank you very much, when using the latest version everything worked perfectly fine. You saved my day! Thanks again!

Best regards,
Sara
________________________________
