### ISSUE TITLE
PROPKA 3.0 rejecting files accepted by PROPKA 1.0

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#55]
A known list of pdb files will not work with PROPKA 3.0 or 3.1. These will will work with PROPKA 1.0. This is probably due to the fallback mechanism not being implemented properly for unknown residues.

@kmonson TODO: Dig up files from email and attach to this ticket.

**Comment by lizutah** [comment]
@kmonson - is there an update on this?

**Comment by kmonson** [comment]
I've got a fix for what I think is a majority of the rejections by PROPKA 3.0 that is checked in.
