### ISSUE TITLE
Clean up vestigal Opal & web server files

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#558]

**Comment by sobolevnrm** [comment]
@intendo and @kozlac -- I think these are all gone as of (at least) a6e43df9ceaa14c619c10c9a755782173fdceb41.  Should we close this issue?

**Comment by intendo** [comment]
I can't find any files. I think we can close it. We can always reopen it if we find any strays left around or generated.
