### ISSUE TITLE
APBS and Python3

### ISSUE THREAD

**Issue by sagitter** [Electrostatics/apbs-pdb2pqr#599]
Hi all.

Does exist any working patch for using APBS-1.5 with Python3?

**Comment by sobolevnrm** [comment]
Yes, the current version of APBS in the Git repo (
https://github.com/Electrostatics/apbs-pdb2pqr/tree/master/apbs) works with
Python 3.

**Comment by sagitter** [comment]
Thank you @sobolevnrm 
When will be out next release?

**Comment by sobolevnrm** [comment]
Hopefully within the next few weeks.  I'll defer to @intendo for details.

**Comment by sagitter** [comment]
> Hopefully within the next few weeks. I'll defer to @intendo for details.

Release 3.0.0, i presume.

**Comment by sobolevnrm** [comment]
Yes, that's correct.

**Comment by sagitter** [comment]
Thank you.

**Comment by intendo** [comment]
@sagitter we are in the final stages of getting APBS working on all the platforms and updating Travis CI and Github Actions to make it easier and faster to make new releases in the future.

Thanks.
