### ISSUE TITLE
PyMOL 2.4.0 APBS plug-in not recognising PDB2PQR

### ISSUE THREAD

**Issue by DBradley27** [Electrostatics/apbs-pdb2pqr#600]
I am using Ubuntu 14.04 on a 64-bit machine. I recently installed an open source version of PyMOL (PyMOL 2.4.0) on my laptop. While the APBS Tools 2.1 plugin is functional, it does not seem compatible with the PDB2PQR software provided in this repository.

I have tried to set the path of the pdb2pqr.py script, but the following error message is returned (truncated):

`File "/usr/lib/python3.4/imp.py", line 210, in load_package
    raise ValueError('{!r} is not a package'.format(path))
ValueError: '/Software/apbs-pdb2pqr-master/pdb2pqr/__init__.py/__init__.pyc' is not a package`

I have invested 12+ hours into trying to solve this issue but with no success. Any help would be appreciated. Thank you.

**Comment by sobolevnrm** [comment]
Can you please provide more information about the version of PDB2PQR you are using?

@speleo3 - do you have any ideas?

Thanks

**Comment by DBradley27** [comment]
Hi. I downloaded everything yesterday from here, so the apbs-pdb2pqr version is 3_0_0 I think.

**Comment by speleo3** [comment]
I suggest:
1) Try the APBS plugin from https://github.com/Pymol-Scripts/Pymol-script-repo/blob/master/plugins/apbsplugin.py which invokes pdb2pqr in a different way than the version which is bundled with Open-Source PyMOL
2) Use pdb2pqr 2.1.1, not 3.0.0 which is currently under active development and may not have been tested yet with the old APBS plugin

**Comment by DBradley27** [comment]
The changes that you suggested worked for me. I can now run PDB2PQR in the Open-Source PyMOL. Thank you very much.
