### ISSUE TITLE
NotImplementedError: PDB2PKA not implemented.

### ISSUE THREAD

**Issue by arikat** [Electrostatics/apbs-pdb2pqr#615]
Unsure why this error continuously pops up. After general installation of the program, I run the command: 

`python3 pdb2pqr.py --ff PARSE --titration-state-method pdb2pka --pdb2pka-out temp/ /home/user/Desktop/tidy.pdb /home/user/Desktop/PDB2PQR/out_files/output.pqr`

The following error appears (log file attached). Unsure why this is the case. Any help would be appreciated.
[txt.txt](https://github.com/Electrostatics/apbs-pdb2pqr/files/4828401/txt.txt)

**Comment by sobolevnrm** [comment]
Hi --

This is the intended behavior for the current master.  Please use one of our releases (and associated tagged branches) instead:  https://github.com/Electrostatics/apbs-pdb2pqr/releases

Thank you,

Nathan

**Comment by arikat** [comment]
I tried some of the other releases. However, they all appear to provide the same error. Is there a specific release you'd recommend? One of the recommendations in the code was to just use pka.py as a standalone script, but it has a number of dependencies in the release, and many of its imports no longer function properly. The read_pdb definition is no longer in pdb.py, for example, it's in input_output.py/. Many other dependencies behave similarly. Should I be changing the imports to make it function properly?

**Comment by sobolevnrm** [comment]
This release should work as expected:  https://github.com/Electrostatics/apbs-pdb2pqr/releases/tag/vPDB2PQR-2.1.1

We're actively working to fix the issues you described in the current release -- that's why we've disabled PDB2PQR in the master branch.  There was a lot of redundant and malfunctioning code that we are trying to clean up.

**Comment by kozlac** [comment]
What python version are you using? You should use python 2.7 for releases <= 2.1.1.

**Comment by arikat** [comment]
I have both, but Python 2.7 is what I'm using for those releases.


________________________

Aarya Venkat

Biochemistry PhD Student, Kannan Lab

Future Faculty Fellow

University of Georgia

https://arikat.github.io/

________________________________

**Comment by kozlac** [comment]
@arikat If you are still seeing that error, can you provide is with OS, python version, which distribution (e.g. apbs-pdb2pqr-vPDB2PQR-2.1.1-release.tar.gz, apbs-pdb2pqr-vPDB2PQR-2.1.1-release.zip, etc.), how are you invoking pdb2pqr from the command line, and if possible the pdf file as well? Thanks!

**Comment by arikat** [comment]
I used apbs-pdb2pqr-vPDB2PQR-2.1.1-release.tar.gz.

OS: Ubuntu 18

Python: 2.7

PDB: 1T8L (which we removed extraneous details like Remarks from)

Command line: python3 pdb2pqr.py --ff PARSE --titration-state-method pdb2pka --pdb2pka-out temp/ /home/user/Desktop/tidy.pdb /home/user/Desktop/PDB2PQR/out_files/output.pqr

Specifically we're trying to use the pdb2pka method. The regular pdb2pqr method works fine.

Thank you for helping!

Kind regards,
Aarya

________________________

Aarya Venkat

Biochemistry PhD Student, Kannan Lab

Future Faculty Fellow

University of Georgia

https://arikat.github.io/

________________________________

**Comment by sobolevnrm** [comment]
@kozlac - could you please look into this?

**Comment by kozlac** [comment]
Hello @arikat, a couple of things:

* You are using `python3` in your command line which invokes python 3.6 by default in Ubuntu 18.
* You are using arguments from the most recent version of pdb2pqr which is still in development (e.g. titration-state-method).

I downloaded [this version](https://github.com/Electrostatics/apbs-pdb2pqr/releases/download/vPDB2PQR-2.1.1/pdb2pqr-linux-bin64-2.1.1.tar.gz) and the 1t8l.pdb from the PDB website and ran the following command successfully: 

`pdb2pqr --ff parse --ph-calc-method pdb2pka --pdb2pka-out ./temp 1t8l.pdb output.pqr`

Notice you don't need to put `python` at the beginning of the command. Please let me know if you have any problems. Thanks!

**Comment by arikat** [comment]
Sorry, the python3 was a typo. I'll try this command thanks!


________________________

Aarya Venkat

Biochemistry PhD Student, Kannan Lab

Future Faculty Fellow

University of Georgia

https://arikat.github.io/

________________________________

**Comment by arikat** [comment]
This command worked, thank you!


________________________

Aarya Venkat

Biochemistry PhD Student, Kannan Lab

Future Faculty Fellow

University of Georgia

https://arikat.github.io/

________________________________

**Comment by kozlac** [comment]
Great!
