### ISSUE TITLE
Move PDB2PQR back to its own repo?

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#619]
Since PDB2PQR is now its own package -- thanks to @kozlac -- I wonder if we should move it back to its own repo.  It would make it *much* easier to release via PyPI and could simplify the APBS installation process and repo.

What do you think?  I'd love to envision a future where someone could `pip install apbs` and automatically grab pdb2pqr and propka as dependencies.  Making PDB2PQR discoverable via PyPI would be a great start for this.

**Comment by sobolevnrm** [comment]
> I like the idea of a separate `pdb2pqr` repo. The only downside I see is that git history will be lost, but I think the benefits you listed will outweigh this.

There may be a way to move over the git history and prune out the APBS history to keep the archive size reasonable.

**Comment by intendo** [comment]
Following the instructions on https://help.github.com/en/github/using-git/splitting-a-subfolder-out-into-a-new-repository, we could create a repository for apbs and pdb2pqr by splitting them. They would each have their respective histories intact (at least from their top level directory).

I created a new empty repository for pdb2pqr (https://github.com/Electrostatics/pdb2pqr) using the following:
    mkdir split && cd split/
    git clone https://github.com/Electrostatics/apbs-pdb2pqr.git
    cd apbs-pdb2pqr/
    git filter-branch --prune-empty --subdirectory-filter pdb2pqr/ master
    git remote add origin https://github.com/Electrostatics/pdb2pqr.git
    git remote set-url origin https://github.com/Electrostatics/pdb2pqr.git
    git push -u origin master

@sobolevnrm and @kozlac can you set the new repository and see if it has everything we need to make pdb2pqr a release on PyPI?

**Comment by sobolevnrm** [comment]
Hi @intendo -- wow!  Thanks for moving this over.  However, now I'm confused:  was this an existence proof or an actual migration of the repo?  If the latter, we need to figure out what to do with the code in the main apbs-pdb2pqr repo.  We can transfer issues but I'm unsure how to move branches given the differences between repositories.  However, these repos are going to get out of sync very quickly.  Can you make the new repo read-only while we figure this out?

**Comment by intendo** [comment]
This was proof that it can be done. Branches on apbs-pdb2pqr can be pushed to the new pdb2pqr repo and then deleted.
I think the procedure is:
  # go to your directory where your current apbs-pdb2pqr repo is
  # checkout the branch you want to push (e.g. nathan/pdb2pka)
  git remote add pdb2pqr https://github.com/Electrostatics/pdb2pqr
  git push pdb2pqr 
  # repeat for all your branches you want to move to the new repository

I can only make the pdb2pqr read only for 24 hours at a time. 

If you want, we can delete this and we can do it again. It only takes about 10 minutes.

**Comment by sobolevnrm** [comment]
I love the forward-leaning nature of this and think we should proceed -- you took a huge jump I was hesitating on and made the right move.

Here are my thoughts on some next steps:

* [ ] @sobolevnrm and @intendo transfer relevant issues to the new repo
* [ ] @sobolevnrm squats on pdb2pqr PyPI package name
* [ ] @sobolevnrm moves any remaining branches to the new repo (probably with manual diffs because he doesn't believe that the procedure @intendo outlined will work)
* [ ] @sobolevnrm and @intendo `git delete` (but not `git filter-branch`) pdb2pqr code from `apbs-pdb2pqr` repo
* [ ] @sobolevnrm and @intendo rename `apbs-pdb2pqr` repo to `apbs`
* [ ] @sobolevnrm updates documentation for `apbs`, `pdb2pqr`, and http://www.poissonboltzmann.org/
* [ ] @sobolevnrm continues to fix PDB2PKA
* [ ] @intendo makes a PyPI package for APBS to satisfy PDB2PKA dependencies

What do you think?

**Comment by intendo** [comment]
My thoughts were to:
- [ ] split out pdb2pqr into a new repository for new organization/development.
- [ ] split out (or duplicate and then git delete) apbs into a new repository for new organization/development
- [ ] leave apbs-pdb2pqr for maintenance of APBS-PDB2PQR 3.0 release

**Comment by sobolevnrm** [comment]
That works for me *if* we leave the `apbs-pdb2pqr` repo HEAD mostly empty with a README.md that points to the new locations.  The release was tagged and will still be available in the archive but I don't want to create confusion by duplicating code in different repos.  What do you think?

**Comment by intendo** [comment]
That works for me too. I have started moving pdb2pqr issues to the new repo.

**Comment by sobolevnrm** [comment]
This thread is too messy:  I've put the APBS-specific tasks in https://github.com/Electrostatics/apbs-pdb2pqr/issues/626 and moved the PDB2PQR-specific tasks over to https://github.com/Electrostatics/pdb2pqr/issues
