### ISSUE TITLE
Port Emilie's pKa Java code into Python 

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#62]

**Comment by lizutah** [comment]
duplicate of #230, closing.

**Comment by lizutah** [comment]
Clarifying this issue:  This is the coversion of Emilie's command line version of the graph cut code into python.

**Comment by lizutah** [comment]
close?

**Comment by kmonson** [comment]
Not yet, working through a few issues.

**Comment by kmonson** [comment]
We'll close this and track any remaining issues in the issues for https://github.com/Electrostatics/graphcut
