### ISSUE TITLE
Positive potential on hydrophobic protein interfaces

### ISSUE THREAD

**Issue by aritzroa** [Electrostatics/apbs-pdb2pqr#623]
Hi all,

I am using the APBS plugin in PyMol and when I use it to calculate the electrostatic potential of a complex I get a positive electrostatic potential in an interface between two of the protein chains. However, the residues are hydrophobic and if I run them separately this same region is completely neutral. Can it be because both interfaces are too close and the APBS program does not manage to recognise it properly as a surface?

**Comment by speleo3** [comment]
Can you attach your input files?

**Comment by aritzroa** [comment]
So I think I found out the reason after all. I can get more precise result by reducing the grid spacing. It is still not optimal, but I guess it is related to a difficulty of the programme to properly estimated two close surfaces based on the grid spacing. It is not possible for my computer go down from 0.2 but it improves. At the end I think the choice would be running the APBS of each protein separately so it gives something more similar to reality.
Would that be reasonable?

**Comment by sobolevnrm** [comment]
Hi @aritzroa -- that makes sense.  I typically recommend grid spacings of 0.2 Å or lower for calculations that require quantitative results or detailed analysis.  Thanks.
