### ISSUE TITLE
Improve APBS test cases with intermediate result analysis

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#64]
Many of the APBS test cases produce results at the intermediate stages of the calculations that can provide additional information for ensuring agreement between versions (and identifying the source of disagreement when it occurs).  In addition to using the final output (e.g., from the PRINT statement), we should include this intermediate output in our test cases' checking behavior.

**Comment by keith923** [comment]
This is a great idea.  I'm not sure how to implement it though.  On one hand, if all of the intermediate calculations are not available via .in file commands, then we'll need to add support for those.  The bigger issue in my mind is: where do we get the ground truth values to compare against?

These may both be non-issues, and I just don't know it.

**Comment by sobolevnrm** [comment]
Hi Keith --

There is intermediate output from various ELEC blocks that could be parsed
by the test script.

**Comment by keith923** [comment]
And for ground truth?  Where can I go to find the expected values for each of the intermediate steps, for each of the tests?

**Comment by sobolevnrm** [comment]
This is primarily a regression test, so referring to results from past
versions of the code is sufficient.

**Comment by kmonson** [comment]
Did you mean to assign this to Keith?

**Comment by kozlac** [comment]
@sobolevnrm were you thinking on something like writing the intermediate charge or pot from the elec block to files and then compare them to previous apbs versions?

**Comment by sobolevnrm** [comment]
I think writing the intermediate energies in mg-para and mg-auto
calculations would be a good start.

**Comment by lizutah** [comment]
Reading intermediate results and comparing them, but need to modify all the test cases and run against builds.  Still in progress (moving to next milestone).

**Comment by kozlac** [comment]
Finish the python code to extract intermediate energies and added the the expected values to the cfg file as well (https://github.com/Electrostatics/apbs-pdb2pqr/commit/34edf403d74cd0acd4061b44d117647cc6acb29d)[64edf40]). Do we want to keep this issue open in case we add more test instances or can we close it?

**Comment by lizutah** [comment]
we can close it!
