### ISSUE TITLE
Documentation target for build system

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#66]
Can we have Doxygen run automatically on the APBS source?

**Comment by keith923** [comment]
Doxygen will run automatically as part of the make process if cmake is invoked with -DBUILD_DOC=ON.

**Comment by sobolevnrm** [comment]
Can that be the default option?

**Comment by keith923** [comment]
##Unintended Consequences
It would seem that our Travis CI build actually *is* doing something useful.  I don't think it's testing, but it *is* building, and it uncovered an issue with defaulting to building the documentation: missing Doxygen causes CMake to fail.

I'll need to update the doc-building cmake code to not fail if Doxygen is missing, and instead just print something out that lets the user they need Doxygen to build the docs.
