### ISSUE TITLE
Robust stand-alone treecode implementation in APBS

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#69]
A standalone treecode method would support
- Faster RPBE setup and solution
- BEM calculations

Can we separate out the treecode part of the BEM code and reuse it for RPBE?

**Comment by lwwilson1** [comment]
I'm curious about this -- I have a working cluster-particle treecode in C I've built this summer that can do Coulomb and screened Coulomb potentials; it's just a function that takes in targets, sources, and some parameters, and returns potentials at the targets. I'm working of course on trying to build a regularized Poisson-Boltzmann solver around it, but could it also be useful as, say, a standalone Sphinx plugin, if some method comes along and needs a similar calculation?

**Comment by keith923** [comment]
That sounds reasonable @lwwilson1. I'm not knowledgeable enough wrt the math and chem exactly how it would fit in a Sphinx pipeline. @sobolevnrm can clarify that though.
