### ISSUE TITLE
APBS Handle other header records besides REMARK

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#77]
Currently APBS fails if header records other than REMARK exist in a pqr file.

The pqr spec is basically "everything in pdb with a few columns changed". This means that APBS should at least be able to handle files with other record types even if it only ignores them:  SPRSDE HEADER TITLE COMPND SOURCE KEYWDS EXPDTA AUTHOR REVDAT JRNL REMARK

**Comment by lizutah** [comment]
duplicate of #214 ?
