### ISSUE TITLE
Make available more features of PROPKA via PDB2PQR

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#80]
Most of the features of PROPKA 3.0 are hidden from the user.

We need to decide what should be added to the PDB2PQR command line and the web interface and well... add it.

Currently implemented in monson-dev branch:

* pH <-doesn't work without this.
* verbose (not going to bother with silent, mute, etc. as we do not have a pdb2pqr equivalent)
* reference - defaults to neutral

To consider:

* --chain=CHAINS creating the protein with only a specified chain, note, chains without ID are labeled 'A' [all] (Probably not as there is nothing that maps well from pdb2pqr.)
* --thermophile=THERMOPHILES defining a thermophile filename; usually used in 'alignment-mutations'
* --alignment=ALIGNMENT alignment file connecting <filename> and <thermophile> [<thermophile>.pir]
* --mutation=MUTATIONS specifying mutation labels which is used to modify <filename> according to, e.g. N25R/N181D
* --version=VERSION_LABEL specifying the sub-version of propka [Jan15/Dec19]
* --protonation=PROTONATION setting protonation scheme
* --window=WINDOW setting the pH-window to show e.g. stability profiles [0.0, 14.0, 1.0]
* --grid=GRID setting the pH-grid to calculate e.g. stability related properties [0.0, 14.0, 0.1]
* --mutator=MUTATOR setting approach for mutating <filename> [alignment/scwrl/jackal]
* --mutator-option=MUTATOR_OPTIONS setting property for mutator [e.g. type="side-chain"]
* --display-coupled-residues Displays alternative pKa values due to coupling of titratable groups
* --print-iterations Displays the pKa iterations in the Tanford-Roxby scheme

**Comment by kmonson** [comment]
This was originally my suggestion. I've only seen one request (in 5 years) to add any PROPKA functionality to PDB2PQR. It was the mutation option that would have required major work in PBD2PQR to make it work and was outside the scope of PDB2PQR in general. I looked in to some of these a while back and most are not trivial or not useful to PDB2PQR users. 

I'm closing this as will not fix. If any come up on the mailing list again we'll address them then.
