### ISSUE TITLE
Write out DX files during focusing calculations

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#84]
Submitted: 2005-10-05 04:46:52 PDT

It would be useful to be able to write out data during
intermediate stages of an automatic focusing
calculations. Ideally, this would be accomplished via
a multi-resolution data format (see related RFE) but
could also be done through judicious renaming of the
output... Of course, this also suggests the ability to
read in this data for later (automatic) focusing
calculations...

Date: 2008-05-23 09:58:18 PDT
Sender: sobolevnrmSourceForge.net

A related issue/feature was requested by a user:

> However, if I were to maintain the same resolution for both the
> dielectric grid and elec calculation, is there an option to read only
> part of the dielectric map for the finer grid calculation of an
> asynchronous parallel run?

This is a good point. We basically need to support adaptive
multi-resolution maps for both input and output. Note that APBS already
has a data structure for this
(http://apbs.sourceforge.net/doc/programmer/html/group__Vmgrid.html) and
OpenDX supports a multigrid format
(http://opendx.sdsc.edu/docs/html/pages/usrgu068.htm#Header_437), so this
shouldn't be too bad to implement.

**Comment by kozlac** [comment]
Do we want this like a flag or a feature that is always on?

**Comment by lizutah** [comment]
I assume a flag, but @sobolevnrm should weigh in.

**Comment by sobolevnrm** [comment]
Yes, a flag would be great.
