### ISSUE TITLE
Create ability to add multiple pH values on PDB2PQR web server

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#96]
Extend the PROPKA feature of the PDB2PQR webservice to automate multiple calculations of the same structure at multiple pH values. Instead of generating a single set of output, multiple sets of output would be automatically generated for each pH.

**Comment by kmonson** [comment]
This seems like it's outside the scope of the web interface in general. We have binaries for all the major platforms that we can refer them to. Should we close this?

**Comment by sobolevnrm** [comment]
If we get the graph-cut PDB2PKA done, then we can close this as "complete"!
